# Generated by Django 5.0.6 on 2024-10-04 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RMSyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rm_id",
                    models.CharField(
                        help_text="User ID in Resource Manager", max_length=255
                    ),
                ),
                ("last_synced", models.DateTimeField()),
                (
                    "sync_enabled",
                    models.BooleanField(
                        default=False, help_text="Should sync schedules"
                    ),
                ),
                (
                    "sync_authoritative",
                    models.BooleanField(
                        default=False,
                        help_text="Removes all non-CHAOTICA time slots. Effectively takes full control.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rm_sync_record",
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
    ]
