# Generated by Django 5.0.6 on 2024-10-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmsyncrecord",
            name="last_synced",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
