# Generated by Django 5.0.6 on 2024-10-04 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0002_alter_rmsyncrecord_last_synced"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmsyncrecord",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_sync_record",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
