# Generated by Django 5.0.6 on 2024-10-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0004_rmsyncrecord_last_sync_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmsyncrecord",
            name="rm_user_data",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
