# Generated by Django 5.0.6 on 2024-10-07 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0027_alter_project_options_and_more"),
        ("rm_sync", "0005_rmsyncrecord_rm_user_data"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rmsyncrecord",
            old_name="rm_user_data",
            new_name="rm_data",
        ),
        migrations.CreateModel(
            name="RMAssignable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rm_id",
                    models.CharField(
                        help_text="Assignable ID in Resource Manager", max_length=255
                    ),
                ),
                ("rm_data", models.JSONField(blank=True, default=list)),
                (
                    "phase",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rm_assignable",
                        to="jobtracker.phase",
                    ),
                ),
            ],
        ),
    ]
