# Generated by Django 5.0.6 on 2024-10-07 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0027_alter_project_options_and_more"),
        ("rm_sync", "0007_rmassignable_last_sync_result_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmassignable",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.project",
            ),
        ),
        migrations.AlterField(
            model_name="rmassignable",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.phase",
            ),
        ),
    ]
