# Generated by Django 5.0.6 on 2024-10-07 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0027_alter_project_options_and_more"),
        ("rm_sync", "0008_rmassignable_project_alter_rmassignable_phase"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rmassignable",
            options={"ordering": ["rm_id"]},
        ),
        migrations.CreateModel(
            name="RMAssignableSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rm_id",
                    models.CharField(
                        blank=True,
                        help_text="Assignable ID in Resource Manager",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("rm_data", models.JSONField(blank=True, default=list)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                ("last_sync_result", models.BooleanField(default=False)),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rm_assignable",
                        to="jobtracker.timeslot",
                    ),
                ),
            ],
            options={
                "ordering": ["rm_id"],
            },
        ),
    ]
