# Generated by Django 5.0.6 on 2024-10-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0028_historicaltimeslot_updated_timeslot_updated"),
        ("rm_sync", "0009_alter_rmassignable_options_rmassignableslot"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmassignable",
            name="slotType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.timeslottype",
            ),
        ),
    ]
