# Generated by Django 5.0.6 on 2024-10-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0028_historicaltimeslot_updated_timeslot_updated"),
        ("rm_sync", "0010_rmassignable_slottype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmassignable",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.phase",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rmassignable",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.project",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rmassignable",
            name="slotType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.timeslottype",
                unique=True,
            ),
        ),
    ]
