# Generated by Django 5.0.6 on 2024-10-10 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0028_historicaltimeslot_updated_timeslot_updated"),
        (
            "rm_sync",
            "0011_alter_rmassignable_phase_alter_rmassignable_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="rmassignable",
            name="phase",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.phase",
            ),
        ),
        migrations.AlterField(
            model_name="rmassignable",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.project",
            ),
        ),
        migrations.AlterField(
            model_name="rmassignable",
            name="slotType",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rm_assignable",
                to="jobtracker.timeslottype",
            ),
        ),
    ]
