# Generated by Django 5.0.6 on 2024-10-10 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0028_historicaltimeslot_updated_timeslot_updated"),
        (
            "rm_sync",
            "0012_alter_rmassignable_phase_alter_rmassignable_project_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rmassignableslot",
            name="id",
        ),
        migrations.AlterField(
            model_name="rmassignable",
            name="rm_id",
            field=models.CharField(
                blank=True,
                help_text="Assignable ID in Resource Manager",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rmassignableslot",
            name="rm_id",
            field=models.CharField(
                blank=True,
                help_text="Assignable ID in Resource Manager",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="rmassignableslot",
            name="slot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="rm_assignable",
                serialize=False,
                to="jobtracker.timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="rmsyncrecord",
            name="rm_id",
            field=models.CharField(
                help_text="User ID in Resource Manager", max_length=255, unique=True
            ),
        ),
    ]
