# Generated by Django 5.0.6 on 2024-10-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rm_sync",
            "0013_remove_rmassignableslot_id_alter_rmassignable_rm_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RMTaskLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("started", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="rmsyncrecord",
            name="sync_in_progress",
            field=models.BooleanField(default=False),
        ),
    ]
