# Generated by Django 5.0.6 on 2024-10-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0014_rmtasklock_rmsyncrecord_sync_in_progress"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmtasklock",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
