# Generated by Django 5.2.12 on 2026-07-30 10:26

from django.db import migrations, models


def enabled_to_direction(apps, schema_editor):
    """Preserve behaviour: previously-enabled records were push-only, so map
    sync_enabled=True -> PUSH (1), everything else stays OFF (0).
    sync_authoritative is retained unchanged and remains orthogonal.
    """
    RMSyncRecord = apps.get_model("rm_sync", "RMSyncRecord")
    RMSyncRecord.objects.filter(sync_enabled=True).update(direction=1)


def direction_to_enabled(apps, schema_editor):
    RMSyncRecord = apps.get_model("rm_sync", "RMSyncRecord")
    RMSyncRecord.objects.filter(direction__in=[1, 2]).update(sync_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0015_rmtasklock_last_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmsyncrecord",
            name="direction",
            field=models.IntegerField(
                choices=[
                    (0, "Off"),
                    (1, "Push (CHAOTICA → RM)"),
                    (2, "Pull (RM → CHAOTICA)"),
                ],
                default=0,
                help_text="OFF = no sync. PUSH = CHAOTICA is the source of truth (mirror to RM). PULL = RM is the source of truth (import into CHAOTICA).",
            ),
        ),
        migrations.RunPython(enabled_to_direction, direction_to_enabled),
        migrations.RemoveField(
            model_name="rmsyncrecord",
            name="sync_enabled",
        ),
        migrations.AlterField(
            model_name="rmsyncrecord",
            name="sync_authoritative",
            field=models.BooleanField(
                default=False,
                help_text="Prune the destination to match the source. For PUSH: delete RM assignments unknown to CHAOTICA. For PULL: delete CHAOTICA RM-origin slots absent from RM. When off, the sync only adds/updates and never deletes.",
            ),
        ),
    ]
