# Generated by Django 5.2.12 on 2026-07-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0072_historicalproject_external_url_project_external_url"),
        ("rm_sync", "0016_remove_rmsyncrecord_sync_enabled_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RMInboundSlot",
            fields=[
                (
                    "timeslot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="rm_inbound",
                        serialize=False,
                        to="jobtracker.timeslot",
                    ),
                ),
                (
                    "rm_assignment_id",
                    models.CharField(
                        db_index=True,
                        help_text="Assignment ID in Resource Manager (not unique — may fan out to N slots).",
                        max_length=255,
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        blank=True,
                        help_text="For fanned-out partial allocations, the day this slot represents.",
                        null=True,
                    ),
                ),
                ("rm_data", models.JSONField(blank=True, default=dict)),
                ("last_synced", models.DateTimeField(blank=True, null=True)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_slots",
                        to="rm_sync.rmsyncrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["record", "rm_assignment_id", "day"],
                "unique_together": {("record", "rm_assignment_id", "day")},
            },
        ),
    ]
