# Generated by Django 5.2.12 on 2026-07-30 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0072_historicalproject_external_url_project_external_url"),
        ("rm_sync", "0017_rminboundslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="RMUnitMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "market_unit",
                    models.CharField(
                        help_text="RM 'Market Unit' custom-field value, e.g. 'UKI' or 'Iberia'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[
                            (0, "Off"),
                            (1, "Push (CHAOTICA → RM)"),
                            (2, "Pull (RM → CHAOTICA)"),
                        ],
                        default=0,
                        help_text="Sync direction applied to users in this market unit.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Only enabled maps assign OU/direction when applying.",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="CHAOTICA org unit these users belong to. Leave blank to map later.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rm_unit_maps",
                        to="jobtracker.organisationalunit",
                    ),
                ),
            ],
            options={
                "ordering": ["market_unit"],
            },
        ),
    ]
