# Generated by Django 5.2.12 on 2026-07-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0018_rmunitmap"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmsyncrecord",
            name="market_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RM 'Market Unit' for this user (drives OU/direction via RMUnitMap).",
                max_length=255,
            ),
        ),
    ]
