# Generated by Django 5.2.12 on 2026-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rm_sync", "0019_rmsyncrecord_market_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="rmsyncrecord",
            name="rm_role",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RM 'role' for this user (mapped to an org-unit role on their membership).",
                max_length=255,
            ),
        ),
    ]
