# Generated by Django 5.0.6 on 2025-03-26 22:55

import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Report Categories",
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this report will be available to all users",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "data_area",
                    models.CharField(
                        help_text="The primary data focus of the report (e.g. 'user', 'job', 'phase')",
                        max_length=100,
                    ),
                ),
                (
                    "population_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters to refine the population (e.g. 'active users only')",
                    ),
                ),
                (
                    "selected_fields",
                    models.JSONField(
                        default=list,
                        help_text="List of fields/columns to display in the report",
                    ),
                ),
                (
                    "filter_conditions",
                    models.JSONField(
                        default=list,
                        help_text="Filter conditions to apply to the report",
                    ),
                ),
                (
                    "sort_order",
                    models.JSONField(
                        default=list,
                        help_text="Fields to sort by and direction (asc/desc)",
                    ),
                ),
                (
                    "default_presentation",
                    models.CharField(
                        choices=[
                            ("excel", "Excel Spreadsheet"),
                            ("html", "Web Page (HTML)"),
                            ("pdf", "PDF Document"),
                            ("text", "Text File"),
                            ("word", "Word Document"),
                            ("analysis", "Analysis Report"),
                        ],
                        default="excel",
                        max_length=20,
                    ),
                ),
                (
                    "allow_runtime_presentation_choice",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to choose output format at runtime",
                    ),
                ),
                (
                    "presentation_options",
                    models.JSONField(
                        default=dict, help_text="Format-specific presentation options"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="reporting.reportcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalReport",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "is_private",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this report will be available to all users",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("modified_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "data_area",
                    models.CharField(
                        help_text="The primary data focus of the report (e.g. 'user', 'job', 'phase')",
                        max_length=100,
                    ),
                ),
                (
                    "population_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filters to refine the population (e.g. 'active users only')",
                    ),
                ),
                (
                    "selected_fields",
                    models.JSONField(
                        default=list,
                        help_text="List of fields/columns to display in the report",
                    ),
                ),
                (
                    "filter_conditions",
                    models.JSONField(
                        default=list,
                        help_text="Filter conditions to apply to the report",
                    ),
                ),
                (
                    "sort_order",
                    models.JSONField(
                        default=list,
                        help_text="Fields to sort by and direction (asc/desc)",
                    ),
                ),
                (
                    "default_presentation",
                    models.CharField(
                        choices=[
                            ("excel", "Excel Spreadsheet"),
                            ("html", "Web Page (HTML)"),
                            ("pdf", "PDF Document"),
                            ("text", "Text File"),
                            ("word", "Word Document"),
                            ("analysis", "Analysis Report"),
                        ],
                        default="excel",
                        max_length=20,
                    ),
                ),
                (
                    "allow_runtime_presentation_choice",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to choose output format at runtime",
                    ),
                ),
                (
                    "presentation_options",
                    models.JSONField(
                        default=dict, help_text="Format-specific presentation options"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="reporting.reportcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical report",
                "verbose_name_plural": "historical reports",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of week (0-6, where 0 is Monday) for weekly schedules",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month (1-31) for monthly schedules",
                        null=True,
                    ),
                ),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("include_as_attachment", models.BooleanField(default=True)),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Runtime parameters to apply when generating the report",
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        related_name="report_subscriptions", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reporting.report",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedReportOutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="reports/%Y/%m/")),
                ("format", models.CharField(max_length=20)),
                ("file_size", models.PositiveIntegerField(default=0)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_outputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outputs",
                        to="reporting.report",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outputs",
                        to="reporting.reportschedule",
                    ),
                ),
            ],
        ),
    ]
