# Generated by Django 5.0.6 on 2025-04-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="population_filter",
        ),
    ]
