# Generated by Django 5.2.12 on 2026-03-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_remove_report_population_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldtype",
            name="can_aggregate",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reportfield",
            name="aggregation_function",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("count", "Count"),
                    ("sum", "Sum"),
                    ("avg", "Average"),
                    ("min", "Minimum"),
                    ("max", "Maximum"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
