# Generated by Django 5.2.12 on 2026-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_add_aggregation_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='resolver_key',
            field=models.CharField(blank=True, help_text="Key into reporting.resolvers.REPORTING_RESOLVERS; used only when source_type='resolver'.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datafield',
            name='source_type',
            field=models.CharField(choices=[('orm', 'ORM Lookup'), ('resolver', 'Computed Resolver')], default='orm', help_text='How this field is computed: a plain ORM lookup or a whitelisted resolver.', max_length=20),
        ),
    ]
