# Generated by Django 5.2.12 on 2026-07-02 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reporting', '0004_datafield_resolver_key_datafield_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Only used for weekly schedules (0=Monday).', null=True)),
                ('run_time', models.TimeField(help_text='Earliest local time of day to send.')),
                ('last_sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('send_aggregate_to_group', models.BooleanField(default=True, help_text='Send the full report to the recipients below.')),
                ('recipient_emails', models.TextField(blank=True, help_text='Comma- or newline-separated email addresses.')),
                ('email_subject', models.CharField(max_length=255)),
                ('email_template_slug', models.CharField(default='emails/scheduled_report.html', help_text='Template used to render the email body.', max_length=255)),
                ('intro_html', models.TextField(blank=True, help_text='HTML shown above the table.')),
                ('outro_html', models.TextField(blank=True, help_text='HTML shown below the table.')),
                ('attachment_format', models.CharField(blank=True, choices=[('', 'None'), ('csv', 'CSV'), ('excel', 'Excel')], default='', max_length=10)),
                ('filter_overrides', models.JSONField(blank=True, default=dict, help_text="Runtime values for the report's prompted filters, keyed by filter id.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_group', models.ForeignKey(blank=True, help_text='All members of this group also receive the aggregated email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports', to='auth.group')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reporting.report')),
                ('run_as_user', models.ForeignKey(help_text="The report runs with this user's permissions. Use a dedicated reporting account, not a superuser, so restricted data is not leaked.", on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('split_by_field', models.ForeignKey(blank=True, help_text="If set, rows are grouped by this field's value and each value that is a valid email address is sent only its own rows (e.g. the account manager email).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to='reporting.datafield')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['name'],
            },
        ),
    ]
