# Generated by Django 5.2.12 on 2026-07-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_scheduledreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='email_template_slug',
            field=models.CharField(default='reporting/emails/scheduled_report.html', help_text='Template used to render the email body.', max_length=255),
        ),
    ]
