# Generated by Django 5.2.12 on 2026-08-05 12:06

import chaotica_utils.utils.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0007_reportrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="owner",
            field=models.ForeignKey(
                on_delete=models.SET(chaotica_utils.utils.common.get_sentinel_user),
                related_name="created_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
