# Generated by Django 5.0.6 on 2025-04-07 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Notification Category",
                "verbose_name_plural": "Notification Categories",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "System Notification"),
                            (1, "Job Status Change"),
                            (2, "Job Created"),
                            (3, "Phase Status Change"),
                            (4, "Phase Late to TQA"),
                            (5, "Phase Late to PQA"),
                            (13, "Phase TQA Updates"),
                            (14, "Phase PQA Updates"),
                            (6, "Phase Late to Delivery"),
                            (12, "Phase Note Added"),
                            (15, "Phase Feedback"),
                            (7, "Leave Submitted"),
                            (8, "Leave Approved"),
                            (9, "Leave Rejected"),
                            (10, "Leave Cancelled"),
                            (11, "Onboarding Renewal Reminders"),
                        ],
                        default=0,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                ("read", models.BooleanField(default=False)),
                ("is_emailed", models.BooleanField(default=False)),
                ("should_email", models.BooleanField(default=False)),
                ("email_template", models.CharField(default="", max_length=255)),
                ("entity_id", models.IntegerField(blank=True, null=True)),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "icon",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "System Notification"),
                            (1, "Job Status Change"),
                            (2, "Job Created"),
                            (3, "Phase Status Change"),
                            (4, "Phase Late to TQA"),
                            (5, "Phase Late to PQA"),
                            (13, "Phase TQA Updates"),
                            (14, "Phase PQA Updates"),
                            (6, "Phase Late to Delivery"),
                            (12, "Phase Note Added"),
                            (15, "Phase Feedback"),
                            (7, "Leave Submitted"),
                            (8, "Leave Approved"),
                            (9, "Leave Rejected"),
                            (10, "Leave Cancelled"),
                            (11, "Onboarding Renewal Reminders"),
                        ],
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the specific entity (like Job ID, Phase ID) to subscribe to. If empty, subscribes to all of this type.",
                        null=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of entity (Job, Phase, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Subscription",
                "verbose_name_plural": "Notification Subscriptions",
                "unique_together": {
                    ("user", "notification_type", "entity_id", "entity_type")
                },
            },
        ),
    ]
