# Generated by Django 5.0.6 on 2025-04-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0049_alter_historicalorganisationalunit_businesshours_days_and_more",
        ),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "System Notification"),
                            (1, "Job Status Change"),
                            (2, "Job Created"),
                            (3, "Phase Status Change"),
                            (4, "Phase Late to TQA"),
                            (5, "Phase Late to PQA"),
                            (13, "Phase TQA Updates"),
                            (14, "Phase PQA Updates"),
                            (6, "Phase Late to Delivery"),
                            (12, "Phase Note Added"),
                            (15, "Phase Feedback"),
                            (7, "Leave Submitted"),
                            (8, "Leave Approved"),
                            (9, "Leave Rejected"),
                            (10, "Leave Cancelled"),
                            (11, "Onboarding Renewal Reminders"),
                        ],
                        help_text="Notification type this rule applies to",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subscription Rule",
                "verbose_name_plural": "Subscription Rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="PhaseRoleCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role_id", models.IntegerField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_criteria",
                        to="notifications.subscriptionrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrgUnitRoleCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "unit_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobtracker.organisationalunitrole",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_criteria",
                        to="notifications.subscriptionrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JobRoleCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("role_id", models.IntegerField()),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_criteria",
                        to="notifications.subscriptionrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GlobalRoleCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Anonymous"),
                            (1, "Admin"),
                            (2, "Manager"),
                            (3, "Service Delivery"),
                            (4, "Sales Manager"),
                            (5, "Sales Member"),
                            (6, "User"),
                        ]
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_criteria",
                        to="notifications.subscriptionrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DynamicRuleCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("criteria_name", models.CharField(max_length=100)),
                ("parameters", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_criteria",
                        to="notifications.subscriptionrule",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
