# Generated by Django 5.0.6 on 2025-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_subscriptionrule_phaserolecriteria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsubscription",
            name="created_by_rule",
            field=models.BooleanField(
                default=False,
                help_text="Whether this subscription was created automatically by a rule",
            ),
        ),
    ]
