# Generated by Django 5.0.6 on 2025-04-09 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationsubscription_created_by_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsubscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
