# Generated by Django 5.0.6 on 2025-04-09 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notificationsubscription_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOptOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "System Notification"),
                            (1, "Job Status Change"),
                            (2, "Job Created"),
                            (3, "Phase Status Change"),
                            (4, "Phase Late to TQA"),
                            (5, "Phase Late to PQA"),
                            (13, "Phase TQA Updates"),
                            (14, "Phase PQA Updates"),
                            (6, "Phase Late to Delivery"),
                            (12, "Phase Note Added"),
                            (15, "Phase Feedback"),
                            (7, "Leave Submitted"),
                            (8, "Leave Approved"),
                            (9, "Leave Rejected"),
                            (10, "Leave Cancelled"),
                            (11, "Onboarding Renewal Reminders"),
                        ]
                    ),
                ),
                ("entity_type", models.CharField(max_length=255)),
                ("entity_id", models.IntegerField()),
                ("opted_out_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("user", "notification_type", "entity_type", "entity_id")
                },
            },
        ),
    ]
