# Generated by Django 5.2.12 on 2026-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text="Template key - equals the filesystem template path it overrides, e.g. 'emails/leave_requested.html'.", max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='What triggers this email.')),
                ('subject', models.CharField(default='{{ title }}', help_text='Email subject. Supports placeholders, e.g. {{ title }}.', max_length=255)),
                ('body_html', models.TextField(help_text="The editable HTML content of the email. When 'Extends base' is on, this is injected into the shared email shell - do not include <html>/<body> tags.")),
                ('body_text', models.TextField(blank=True, help_text='Optional plain-text version. If blank, the notification message is used.')),
                ('extends_base', models.BooleanField(default=True, help_text='Wrap the content in the shared email_base.html shell (recommended).')),
                ('action_label', models.CharField(default='View', help_text='Text for the call-to-action button (shown when the email has an action link).', max_length=100)),
                ('available_context', models.TextField(blank=True, help_text='Documentation for editors: the placeholders available to this template.')),
                ('is_active', models.BooleanField(default=True, help_text='If off, the filesystem template is used instead (kill-switch).')),
                ('is_seeded', models.BooleanField(default=False, editable=False)),
                ('is_customized', models.BooleanField(default=False, help_text='Set automatically when an admin edits this template; protects it from re-seeding.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
    ]
