# Generated by Django 4.2.2 on 2023-09-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
