# Generated by Django 4.2.2 on 2024-02-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaotica_utils', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contracted_leave',
            field=models.IntegerField(default=25, verbose_name='Contracted Days Leave'),
        ),
    ]
