# Generated by Django 5.0.3 on 2024-04-02 11:12

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("last_name"),
                    django.db.models.functions.text.Lower("first_name"),
                ],
                "permissions": (
                    ("manage_user", "Can manage the user"),
                    ("manage_leave", "Manage leave"),
                    ("impersonate_users", "Can impersonate other users"),
                    ("manage_site_settings", "Can change site settings"),
                ),
            },
        ),
    ]
