# Generated by Django 4.2.2 on 2023-09-18 20:32

import chaotica_utils.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobtracker",
            "0003_rename_chargecode_billingcode_alter_feedback_options_and_more",
        ),
        ("chaotica_utils", "0002_alter_notification_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["last_name"]},
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_on", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateTimeField(db_index=True)),
                ("end_date", models.DateTimeField(db_index=True)),
                (
                    "type_of_leave",
                    models.IntegerField(
                        choices=[
                            (0, "Annual leave"),
                            (1, "Time Off in Lieu"),
                            (2, "Unpaid leave"),
                            (3, "Compassionate leave"),
                            (4, "Paternity/Maternity"),
                            (5, "Jury service"),
                            (6, "Military leave"),
                            (7, "Sick"),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("authorised", models.BooleanField(default=False)),
                ("authorised_on", models.DateTimeField(blank=True, null=True)),
                ("cancelled", models.BooleanField(default=False)),
                ("cancelled_on", models.DateTimeField(blank=True, null=True)),
                ("declined", models.BooleanField(default=False)),
                ("declined_on", models.DateTimeField(blank=True, null=True)),
                (
                    "authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_records_authorised",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "declined_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_records_declined",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jobtracker.timeslot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                        related_name="leave_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
