# Generated by Django 4.2.2 on 2023-10-24 13:05

import chaotica_utils.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pref_timezone",
            field=models.CharField(
                blank=True,
                default="UTC",
                max_length=255,
                null=True,
                verbose_name="Time Zone",
            ),
        ),
        migrations.AlterField(
            model_name="historicalnote",
            name="content",
            field=models.TextField(
                blank=True, help_text="Note Text", verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(
                blank=True, help_text="Note Text", verbose_name="Content"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="contracted_leave",
            field=models.IntegerField(default=0, verbose_name="Contracted Days Leave"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, upload_to=chaotica_utils.models.get_media_profile_file_path
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="show_help",
            field=models.BooleanField(
                default=True,
                help_text="Should help be shown",
                verbose_name="Show Helpful Tips",
            ),
        ),
    ]
