# Generated by Django 4.2.2 on 2023-10-09 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="schedule_feed_family_id",
            field=models.UUIDField(
                default=uuid.uuid4, verbose_name="Calendar Feed Family Key"
            ),
        ),
    ]
