# Generated by Django 4.2.2 on 2023-10-08 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["start_date"], "verbose_name": "Leave Request"},
        ),
        migrations.AddField(
            model_name="user",
            name="contracted_leave",
            field=models.IntegerField(default=0, verbose_name="Contracted Leave"),
        ),
        migrations.AddField(
            model_name="user",
            name="contracted_leave_renewal",
            field=models.DateField(
                default=datetime.date(2023, 9, 1), verbose_name="Contracted Leave"
            ),
        ),
    ]
