# Generated by Django 5.0.3 on 2024-04-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_template",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_emailed",
            field=models.BooleanField(default=False),
        ),
    ]
