# Generated by Django 4.2.2 on 2023-10-24 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "chaotica_utils",
            "0003_user_pref_timezone_alter_historicalnote_content_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invited_email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email Address"
                    ),
                ),
                (
                    "accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Has the invitation been accepted",
                        verbose_name="Accepted",
                    ),
                ),
                (
                    "invite_id",
                    models.UUIDField(default=uuid.uuid4, verbose_name="Invitation ID"),
                ),
                ("sent", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users_invited",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
