# Generated by Django 5.0.6 on 2024-08-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0004_notification_email_template_notification_is_emailed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="If configured, email notifications go to this address rather than your account address.",
                max_length=254,
                verbose_name="Notification Email Address",
            ),
        ),
    ]
