# Generated by Django 4.2.2 on 2023-10-25 13:18

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0004_userinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(default="UK", max_length=2),
        ),
    ]
