# Generated by Django 4.2.2 on 2024-02-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0004_user_profile_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_last_updated",
            field=models.DateField(
                blank=True, null=True, verbose_name="Profile Last Updated"
            ),
        ),
    ]
