# Generated by Django 4.2.2 on 2023-09-18 21:19

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0005_alter_holiday_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                "ordering": ["country"],
            },
        ),
        migrations.AlterField(
            model_name="holiday",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="chaotica_utils.holidaycountry",
            ),
        ),
    ]
