# Generated by Django 4.2.2 on 2023-10-29 12:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0005_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(default="GB", max_length=2),
        ),
    ]
