# Generated by Django 4.2.2 on 2024-02-08 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0005_alter_user_profile_last_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name"],
                "permissions": (("manage_user", "Can manage the user"),),
            },
        ),
    ]
