# Generated by Django 5.0.3 on 2024-03-12 12:51

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="holidaycountry",
            options={"ordering": [django.db.models.functions.text.Lower("country")]},
        ),
        migrations.AlterModelOptions(
            name="language",
            options={
                "ordering": [django.db.models.functions.text.Lower("display_name")]
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("last_name"),
                    django.db.models.functions.text.Lower("first_name"),
                ],
                "permissions": (("manage_user", "Can manage the user"),),
            },
        ),
    ]
