# Generated by Django 4.2.2 on 2023-09-18 21:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0006_holidaycountry_alter_holiday_country"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("date", "country")},
        ),
        migrations.RemoveField(
            model_name="holiday",
            name="subdiv",
        ),
    ]
