# Generated by Django 5.0.3 on 2024-03-12 16:42

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "chaotica_utils",
            "0007_alter_holidaycountry_options_alter_language_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("last_name"),
                    django.db.models.functions.text.Lower("first_name"),
                ],
                "permissions": (
                    ("manage_user", "Can manage the user"),
                    ("impersonate_users", "Can impersonate other users"),
                ),
            },
        ),
    ]
