# Generated by Django 5.0.6 on 2024-08-27 10:16

import datetime
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0007_alter_user_carry_over_leave"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("last_name"),
                    django.db.models.functions.text.Lower("first_name"),
                ],
                "permissions": (
                    ("manage_user", "Can manage the user"),
                    ("manage_leave", "Manage leave"),
                    ("impersonate_users", "Can impersonate other users"),
                    ("manage_site_settings", "Can change site settings"),
                    ("view_activity_logs", "Can review the activity logs"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="carry_over_leave",
            field=models.IntegerField(
                default=0,
                help_text="Days leave carried over from previous period",
                verbose_name="Leave Carried Over",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contracted_leave",
            field=models.IntegerField(
                default=25,
                help_text="Days leave you are entitled to",
                verbose_name="Contracted Leave",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="contracted_leave_renewal",
            field=models.DateField(
                default=datetime.date(2023, 9, 1),
                help_text="Date leave is reset",
                verbose_name="Leave Renewal Date",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="This is your authenticated email and can not be changed",
                max_length=254,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
    ]
