# Generated by Django 4.2.2 on 2023-09-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "chaotica_utils",
            "0007_alter_holiday_unique_together_holiday_subdivs_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="holiday",
            name="subdivs",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
