# Generated by Django 4.2.2 on 2023-09-18 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chaotica_utils", "0008_alter_holiday_subdivs"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("date", "country", "reason")},
        ),
    ]
