# Generated by Django 5.0.6 on 2024-08-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chaotica_utils",
            "0008_alter_user_options_alter_user_carry_over_leave_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="type_of_leave",
            field=models.IntegerField(
                choices=[
                    (0, "Annual leave"),
                    (1, "Time Off in Lieu"),
                    (2, "Unpaid leave"),
                    (3, "Compassionate leave"),
                    (4, "Paternity/Maternity"),
                    (5, "Jury service"),
                    (6, "Military leave"),
                    (7, "Sick"),
                    (8, "Public Holiday"),
                    (9, "Non-Working"),
                    (10, "Excused from Office"),
                    (11, "Other Approved"),
                    (12, "Overtime Leave"),
                    (13, "Medical Appointment"),
                    (14, "Sabbatical Leave"),
                ]
            ),
        ),
    ]
