# Generated by Django 4.2.2 on 2023-09-22 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobtracker",
            "0003_rename_chargecode_billingcode_alter_feedback_options_and_more",
        ),
        ("chaotica_utils", "0009_alter_holiday_unique_together"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LeaveRecord",
            new_name="LeaveRequest",
        ),
    ]
