# Generated by Django 5.0.6 on 2024-09-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0010_alter_leaverequest_authorised_by_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-start_date"], "verbose_name": "Leave Request"},
        ),
    ]
