# Generated by Django 5.0.6 on 2024-10-31 11:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0012_user_latitude_user_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holiday",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.DeleteModel(
            name="HolidayCountry",
        ),
    ]
