# Generated by Django 5.0.6 on 2025-03-06 17:03

import chaotica_utils.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0014_alter_holiday_options_alter_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="acting_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.user.get_sentinel_user),
                related_name="users_acting_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.user.get_sentinel_user),
                related_name="users_managed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                upload_to=chaotica_utils.models.user.get_media_profile_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="usercost",
            name="user",
            field=models.ForeignKey(
                on_delete=models.SET(chaotica_utils.models.user.get_sentinel_user),
                related_name="costs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
