# Generated by Django 5.0.6 on 2025-03-20 21:27

import chaotica_utils.models.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0016_alter_user_pref_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Notification Category",
                "verbose_name_plural": "Notification Categories",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="entity_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.IntegerField(
                choices=[
                    (0, "System Notification"),
                    (1, "Job Status Change"),
                    (2, "Job Created"),
                    (3, "Phase Status Change"),
                    (4, "Phase Late to TQA"),
                    (5, "Phase Late to PQA"),
                    (6, "Phase Late to Delivery"),
                    (7, "Leave Submitted"),
                    (8, "Leave Approved"),
                    (9, "Leave Rejected"),
                    (10, "Added to Organisational Unit"),
                ],
                default=0,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="NotificationSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.IntegerField(
                        choices=[
                            (0, "System Notification"),
                            (1, "Job Status Change"),
                            (2, "Job Created"),
                            (3, "Phase Status Change"),
                            (4, "Phase Late to TQA"),
                            (5, "Phase Late to PQA"),
                            (6, "Phase Late to Delivery"),
                            (7, "Leave Submitted"),
                            (8, "Leave Approved"),
                            (9, "Leave Rejected"),
                            (10, "Added to Organisational Unit"),
                        ],
                        verbose_name="Notification Type",
                    ),
                ),
                (
                    "entity_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID of the specific entity (like Job ID, Phase ID) to subscribe to. If empty, subscribes to all of this type.",
                        null=True,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of entity (Job, Phase, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Subscription",
                "verbose_name_plural": "Notification Subscriptions",
                "unique_together": {
                    ("user", "notification_type", "entity_id", "entity_type")
                },
            },
        ),
    ]
