# Generated by Django 5.0.6 on 2025-03-20 21:34

from django.db import migrations

def clear_existing_notifications(apps, schema_editor):
    Notification = apps.get_model('chaotica_utils', 'Notification')
    # Output the count being deleted (will show in migration output)
    count = Notification.objects.count()
    print(f"Deleting {count} existing notifications")
    Notification.objects.all().delete()

def reverse_func(apps, schema_editor):
    # No reversal action needed
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('chaotica_utils', '0017_notificationcategory_notification_entity_id_and_more'),  # Replace with actual previous migration
    ]

    operations = [
        migrations.RunPython(
            clear_existing_notifications,
            reverse_func,
        ),
    ]