# Generated by Django 5.0.6 on 2025-03-26 22:55

import chaotica_utils.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0018_clear_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="is_read",
        ),
        migrations.AddField(
            model_name="notification",
            name="should_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.IntegerField(
                choices=[
                    (0, "System Notification"),
                    (1, "Job Status Change"),
                    (2, "Job Created"),
                    (3, "Phase Status Change"),
                    (4, "Phase Late to TQA"),
                    (5, "Phase Late to PQA"),
                    (13, "Phase TQA Updates"),
                    (14, "Phase PQA Updates"),
                    (6, "Phase Late to Delivery"),
                    (12, "Phase Note Added"),
                    (15, "Phase Feedback"),
                    (7, "Leave Submitted"),
                    (8, "Leave Approved"),
                    (9, "Leave Rejected"),
                    (10, "Leave Cancelled"),
                    (11, "Onboarding Renewal Reminders"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="notificationsubscription",
            name="notification_type",
            field=models.IntegerField(
                choices=[
                    (0, "System Notification"),
                    (1, "Job Status Change"),
                    (2, "Job Created"),
                    (3, "Phase Status Change"),
                    (4, "Phase Late to TQA"),
                    (5, "Phase Late to PQA"),
                    (13, "Phase TQA Updates"),
                    (14, "Phase PQA Updates"),
                    (6, "Phase Late to Delivery"),
                    (12, "Phase Note Added"),
                    (15, "Phase Feedback"),
                    (7, "Leave Submitted"),
                    (8, "Leave Approved"),
                    (9, "Leave Rejected"),
                    (10, "Leave Cancelled"),
                    (11, "Onboarding Renewal Reminders"),
                ],
                verbose_name="Notification Type",
            ),
        ),
    ]
