# Generated by Django 5.0.6 on 2025-04-07 15:11

import chaotica_utils.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0019_remove_notification_is_read_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="NotificationCategory",
        ),
        migrations.AlterUniqueTogether(
            name="notificationsubscription",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="notificationsubscription",
            name="user",
        ),
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="NotificationSubscription",
        ),
    ]
