# Generated by Django 5.0.6 on 2025-04-07 16:05

import chaotica_utils.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chaotica_utils",
            "0020_remove_notification_user_delete_notificationcategory_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
