# Generated by Django 5.2.3 on 2025-09-04 15:00

import chaotica_utils.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0023_alter_user_managers_alter_note_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualbackupjob",
            name="backup_type",
            field=models.CharField(
                choices=[("media", "Media Backup"), ("db", "Database Backup")],
                default="db",
                max_length=10,
            ),
        ),
    ]
