# Generated by Django 5.2.3 on 2025-09-18 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0025_healthcheckapikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_label",
                    models.CharField(
                        help_text="Short identifier (e.g., 'JL1', 'JL2')",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "long_label",
                    models.CharField(
                        blank=True,
                        help_text="Full description (e.g., 'Job Level 1 - Senior Manager')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Sort order (lower numbers have priority)",
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this level is currently in use"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Job Level",
                "verbose_name_plural": "Job Levels",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserJobLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when this level was assigned",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the user's current level",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the assignment/promotion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="chaotica_utils.joblevel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_level_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Job Level",
                "verbose_name_plural": "User Job Levels",
                "ordering": ["-assigned_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_current"],
                        name="chaotica_ut_user_id_80d023_idx",
                    ),
                    models.Index(
                        fields=["assigned_date"], name="chaotica_ut_assigne_60c6e3_idx"
                    ),
                ],
            },
        ),
    ]
