# Generated by Django 5.2.3 on 2025-11-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0026_joblevel_userjoblevel"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
