# Generated by Django 5.2.3 on 2025-11-26 09:36

import chaotica_utils.utils.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0027_alter_user_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date the quote was created",
                        verbose_name="Created",
                    ),
                ),
                (
                    "mod_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date the quote was last modified",
                        verbose_name="Last Modified",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Note Text", verbose_name="Content"),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Author", max_length=255, verbose_name="Author"
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enabled for showing",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
                "ordering": ["-create_date"],
            },
        ),
    ]
