# Generated by Django 5.2.3 on 2025-12-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0028_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="alias",
            field=models.CharField(
                blank=True,
                default="",
                help_text="A nickname or preferred display name for this user",
                max_length=255,
                null=True,
                verbose_name="Alias/Nickname",
            ),
        ),
    ]
