# Generated by Django 5.2.3 on 2025-12-09 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0029_user_alias"),
        ("cities_light", "0012_city_translations_country_translations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longitude",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="Select your primary city/location",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.city",
                verbose_name="Location",
            ),
        ),
    ]
