# Generated by Django 5.2.3 on 2025-12-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0030_add_city_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Tag name (e.g., Office, VPN, Home)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this tag represents",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Hex color code for the tag badge (e.g., #007bff)",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this tag is active and should be used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IP Tag",
                "verbose_name_plural": "IP Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IPCIDRRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cidr",
                    models.CharField(
                        help_text="CIDR notation (e.g., 192.168.1.0/24 or 2001:db8::/32)",
                        max_length=43,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of this CIDR range",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this CIDR range is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="The tag this CIDR range belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cidrranges",
                        to="chaotica_utils.iptag",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP CIDR Range",
                "verbose_name_plural": "IP CIDR Ranges",
                "ordering": ["tag__name", "cidr"],
                "unique_together": {("tag", "cidr")},
            },
        ),
    ]
