# Generated by Django 5.2.12 on 2026-03-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaotica_utils', '0031_iptag_ipcidrrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='schedule_feed_enabled',
            field=models.BooleanField(default=False, help_text='Allow your schedule to be accessed via the calendar feed URL', verbose_name='Calendar Feed Enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='schedule_feed_family_enabled',
            field=models.BooleanField(default=False, help_text='Allow your family-friendly schedule to be accessed via the calendar feed URL', verbose_name='Family Calendar Feed Enabled'),
        ),
    ]
