# Generated by Django 5.2.12 on 2026-07-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0032_add_calendar_feed_enabled_fields"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["content_type", "object_id"], name="note_ct_obj_idx"
            ),
        ),
    ]
