# Generated by Django 5.2.12 on 2026-08-06 14:11

import chaotica_utils.utils.common
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chaotica_utils", "0036_resync_global_role_permissions"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_repr", models.CharField(blank=True, max_length=255)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("status_change", "Status Changed"),
                            ("assign", "Assigned"),
                            ("unassign", "Unassigned"),
                            ("schedule", "Scheduled"),
                            ("login", "Logged In"),
                            ("logout", "Logged Out"),
                            ("login_failed", "Login Failed"),
                            ("permission_change", "Permissions Changed"),
                            ("token_issued", "Token Issued"),
                            ("token_revoked", "Token Revoked"),
                            ("sync", "Synchronised"),
                            ("export", "Exported"),
                            ("comment", "Commented"),
                            ("link_add", "Link Added"),
                            ("link_remove", "Link Removed"),
                            ("other", "Activity"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("auth", "Authentication"),
                            ("security", "Security"),
                            ("finance", "Finance"),
                            ("config", "Configuration"),
                            ("schedule", "Schedule"),
                            ("workflow", "Workflow"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=24,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("target_id", models.CharField(blank=True, max_length=64, null=True)),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "Web"),
                            ("api", "API"),
                            ("celery", "Background Task"),
                            ("system", "System"),
                            ("rm_sync", "Resource Manager Sync"),
                            ("cli", "Command Line"),
                        ],
                        default="web",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (20, "Info"),
                            (25, "Notice"),
                            (30, "Warning"),
                            (40, "Error"),
                        ],
                        default=20,
                    ),
                ),
                ("changes", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action. Null means the SYSTEM acted.",
                        null=True,
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["target_content_type", "target_id", "-timestamp"],
                        name="audit_target_idx",
                    ),
                    models.Index(
                        fields=["category", "-timestamp"], name="audit_category_idx"
                    ),
                    models.Index(
                        fields=["actor", "-timestamp"], name="audit_actor_idx"
                    ),
                ],
            },
        ),
    ]
