# Generated by Django 4.2.2 on 2023-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="county",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="client",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="To be used when referring to this client in documents such as proposals.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicaladdress",
            name="county",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="short_name",
            field=models.CharField(
                blank=True,
                help_text="To be used when referring to this client in documents such as proposals.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="External ID",
            ),
        ),
    ]
