# Generated by Django 4.2.2 on 2023-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="feedback_scope_correct",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Was scope correct?",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="feedback_scope_correct",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Was scope correct?",
            ),
        ),
    ]
