# Generated by Django 4.2.2 on 2023-10-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0002_alter_historicalphase_feedback_scope_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_completed_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual completed date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_delivery_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual delivered date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_sent_to_pqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual sent to PQA date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_sent_to_tqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual sent to TQA date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_start_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Actual start date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="feedback_scope_correct",
            field=models.BooleanField(
                blank=True,
                choices=[(None, ""), (True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Was scope correct?",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_completed_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual completed date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_delivery_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual delivered date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_sent_to_pqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual sent to PQA date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_sent_to_tqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Actual sent to TQA date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_start_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Actual start date"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="feedback_scope_correct",
            field=models.BooleanField(
                blank=True,
                choices=[(None, ""), (True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Was scope correct?",
            ),
        ),
    ]
