# Generated by Django 4.2.2 on 2024-01-23 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0002_job_indicitive_services"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="indicitive_services",
            new_name="indicative_services",
        ),
    ]
