# Generated by Django 4.2.2 on 2023-09-15 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobtracker", "0002_alter_organisationalunit_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChargeCode",
            new_name="BillingCode",
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_on"], "permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("add_note", "Can Add Note"),
                    ("scope_job", "Can Scope Job"),
                    ("view_schedule", "Can View Schedule"),
                    ("change_schedule", "Can Change Schedule"),
                    ("assign_poc", "Can assign Point of Contact"),
                ),
                "verbose_name": "Job",
            },
        ),
        migrations.AlterField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="written_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feedback",
                to="jobtracker.phase",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeedback",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
