# Generated by Django 4.2.2 on 2023-10-07 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0002_alter_organisationalunit_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("assign_members_organisationalunit", "Assign Members"),
                    ("can_view_unit_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    (
                        "can_view_all_leave_requests",
                        "Can view all leave for members of the unit",
                    ),
                    ("can_approve_leave_requests", "Can approve leave requests"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("can_schedule_phases", "Can schedule phases"),
                ),
            },
        ),
    ]
