# Generated by Django 5.0.3 on 2024-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0002_alter_organisationalunitrole_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="additional_kit_required",
            field=models.BooleanField(
                null=True, verbose_name="Additional kit required"
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="is_restricted",
            field=models.BooleanField(
                null=True, verbose_name="Is the engagement Protectively Marked"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="additional_kit_required",
            field=models.BooleanField(
                null=True, verbose_name="Additional kit required"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="is_restricted",
            field=models.BooleanField(
                null=True, verbose_name="Is the engagement Protectively Marked"
            ),
        ),
    ]
