# Generated by Django 4.2.2 on 2023-10-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0002_alter_address_county_alter_client_external_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField(unique=True, verbose_name="Type ID")),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "built_in",
                    models.BooleanField(
                        default=False, verbose_name="Type is a default type"
                    ),
                ),
                (
                    "is_delivery",
                    models.BooleanField(
                        default=False, verbose_name="Is a delivery type"
                    ),
                ),
                (
                    "availability",
                    models.IntegerField(
                        choices=[
                            (0, "Unavailable"),
                            (1, "Available"),
                            (2, "Busy - Internal"),
                            (3, "Busy - Delivery"),
                        ],
                        default=1,
                        help_text="If resource is available or not",
                        verbose_name="Availability",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="timeslot",
            name="slot_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="jobtracker.timeslottype",
            ),
        ),
    ]
