# Generated by Django 4.2.2 on 2023-10-04 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobtracker",
            "0003_rename_chargecode_billingcode_alter_feedback_options_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaljob",
            old_name="scoping_information",
            new_name="overview",
        ),
        migrations.RenameField(
            model_name="job",
            old_name="scoping_information",
            new_name="overview",
        ),
    ]
