# Generated by Django 5.0.6 on 2024-08-19 14:50

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0003_alter_historicaljob_additional_kit_required_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True, help_text="Description of service", null=True
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=django_bleach.models.BleachField(
                blank=True, help_text="Description of service", null=True
            ),
        ),
    ]
