# Generated by Django 4.2.2 on 2023-10-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0003_alter_organisationalunit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="slotType",
            field=models.IntegerField(
                choices=[
                    (0, "Generic"),
                    (1, "Internal"),
                    (2, "Delivery"),
                    (3, "Leave"),
                ],
                default=0,
                help_text="Type of time",
                verbose_name="Slot Type",
            ),
        ),
    ]
