# Generated by Django 4.2.2 on 2024-01-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobtracker.models.timeslot
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobtracker", "0003_rename_indicitive_services_job_indicative_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTimeSlot",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "deliveryRole",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Delivery"),
                            (2, "Reporting"),
                            (3, "Management"),
                            (4, "QA"),
                            (5, "Oversight"),
                            (6, "Debrief"),
                            (7, "Contingency"),
                            (8, "Shadowing"),
                            (8, "Other"),
                        ],
                        default=0,
                        help_text="Type of role in job",
                        verbose_name="Delivery Type",
                    ),
                ),
                (
                    "is_onsite",
                    models.BooleanField(
                        default=False,
                        help_text="Is this slot onsite",
                        verbose_name="Is onsite",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.phase",
                    ),
                ),
                (
                    "slot_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default=jobtracker.models.timeslot.TimeSlotType.get_default_slot_type,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.timeslottype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to=models.Q(("is_active", True)),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical time slot",
                "verbose_name_plural": "historical time slots",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
