# Generated by Django 4.2.2 on 2023-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobtracker",
            "0004_rename_scoping_information_historicaljob_overview_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("assign_members_organisationalunit", "Assign Members"),
                    ("can_view_unit_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("can_schedule_phases", "Can schedule phases"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="historicalorganisationalunitmember",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Pending Approval"),
                    (1, "Consultant"),
                    (2, "Sales"),
                    (3, "Service Delivery"),
                    (4, "Manager"),
                    (5, "Tech QA'er"),
                    (6, "Pres QA'er"),
                    (7, "Scoper"),
                ],
                default=1,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="organisationalunitmember",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Pending Approval"),
                    (1, "Consultant"),
                    (2, "Sales"),
                    (3, "Service Delivery"),
                    (4, "Manager"),
                    (5, "Tech QA'er"),
                    (6, "Pres QA'er"),
                    (7, "Scoper"),
                ],
                default=1,
                verbose_name="Role",
            ),
        ),
    ]
