# Generated by Django 4.2.2 on 2024-02-06 23:43

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0004_historicaltimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='specific_reporting_requirements',
            field=django_bleach.models.BleachField(blank=True, help_text='Any special reporting requirements', null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='specific_reporting_requirements',
            field=django_bleach.models.BleachField(blank=True, help_text='Any special reporting requirements', null=True),
        ),
    ]
