# Generated by Django 4.2.2 on 2023-10-25 11:35

from django.db import migrations, models
import django.db.models.deletion
import jobtracker.models.timeslot


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0005_remove_timeslottype_type_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="deliveryRole",
            field=models.IntegerField(
                choices=[
                    (0, "None"),
                    (1, "Delivery"),
                    (2, "Reporting"),
                    (3, "Management"),
                    (4, "QA"),
                    (5, "Oversight"),
                    (6, "Debrief"),
                    (7, "Contingency"),
                    (8, "Shadowing"),
                    (8, "Other"),
                ],
                default=0,
                help_text="Type of role in job",
                verbose_name="Delivery Type",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="slot_type",
            field=models.ForeignKey(
                default=jobtracker.models.timeslot.TimeSlotType.get_default_slot_type,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="jobtracker.timeslottype",
            ),
        ),
    ]
