# Generated by Django 4.2.2 on 2024-02-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0005_client_specific_reporting_requirements_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="contingency_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Contingency Hours",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="debrief_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="Debrief Hours"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="delivery_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="Delivery Hours"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="mgmt_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Management Hours",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="other_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="Other Hours"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="oversight_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Oversight Hours",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="qa_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="QA Hours"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="reporting_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Reporting Hours",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="contingency_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Contingency Hours",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="debrief_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="Debrief Hours"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="delivery_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="Delivery Hours"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="mgmt_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Management Hours",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="other_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="Other Hours"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="oversight_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Oversight Hours",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="qa_hours",
            field=models.DecimalField(
                decimal_places=3, default=0, max_digits=6, verbose_name="QA Hours"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="reporting_hours",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=6,
                verbose_name="Reporting Hours",
            ),
        ),
    ]
