# Generated by Django 5.0.6 on 2024-08-19 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0005_historicalservice_link_service_link"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users responsible for the management of the service.",
                limit_choices_to={"is_active": True},
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="skillsDesired",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills desired but not essential",
                related_name="services_skill_desired",
                to="jobtracker.skill",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="skillsRequired",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills required to perform this service",
                related_name="services_skill_required",
                to="jobtracker.skill",
            ),
        ),
    ]
