# Generated by Django 4.2.2 on 2023-10-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0006_alter_timeslot_deliveryrole_alter_timeslot_slot_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeslot",
            name="slotType",
        ),
        migrations.AddField(
            model_name="timeslottype",
            name="is_assignable",
            field=models.BooleanField(default=True, verbose_name="Is Assignable"),
        ),
        migrations.AlterField(
            model_name="timeslottype",
            name="is_working",
            field=models.BooleanField(default=False, verbose_name="Is Working"),
        ),
    ]
