# Generated by Django 4.2.2 on 2024-02-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0006_alter_historicalphase_contingency_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphase",
            name="notifications_late_delivery_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalphase",
            name="notifications_late_pqa_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalphase",
            name="notifications_late_tqa_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalphase",
            name="notifications_workflow_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="notifications_late_delivery_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="notifications_late_pqa_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="notifications_late_tqa_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="notifications_workflow_last_fired",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
