# Generated by Django 5.0.6 on 2024-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0006_alter_service_owners_alter_service_skillsdesired_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalservice",
            name="link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to service information",
                max_length=2000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Link to service information",
                max_length=2000,
                null=True,
            ),
        ),
    ]
