# Generated by Django 4.2.2 on 2023-10-25 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobtracker",
            "0007_remove_timeslot_slottype_timeslottype_is_assignable_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeslottype",
            options={"ordering": ["name"], "verbose_name_plural": "Timeslot Types"},
        ),
    ]
