# Generated by Django 5.0.6 on 2024-08-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0007_alter_historicalservice_link_alter_service_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="jobtracker.skill",
            ),
        ),
    ]
