# Generated by Django 4.2.2 on 2024-02-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "jobtracker",
            "0007_historicalphase_notifications_late_delivery_last_fired_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="phase_number",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="phase",
            name="phase_number",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
