# Generated by Django 5.0.6 on 2024-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0008_alter_userskill_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="description",
            field=models.TextField(
                default="", help_text="A short description of the skill"
            ),
        ),
        migrations.AddField(
            model_name="skillcategory",
            name="description",
            field=models.TextField(
                default="", help_text="A short description of the category"
            ),
        ),
    ]
