# Generated by Django 5.0.3 on 2024-03-12 12:51

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0008_alter_historicalphase_phase_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingcode",
            options={"ordering": [django.db.models.functions.text.Lower("code")]},
        ),
        migrations.AlterModelOptions(
            name="certification",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("view_users_certification", "View Users with Certification"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("assign_account_managers_client", "Assign Account Managers"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("manage_members", "Assign Members"),
                    ("can_view_unit_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    (
                        "can_view_all_leave_requests",
                        "Can view all leave for members of the unit",
                    ),
                    ("can_approve_leave_requests", "Can approve leave requests"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("can_schedule_phases", "Can schedule phases"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (("assign_to_phase", "Assign To Phase"),),
            },
        ),
        migrations.AlterModelOptions(
            name="skill",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("category"),
                    django.db.models.functions.text.Lower("name"),
                ],
                "permissions": (("view_users_skill", "View Users with Skill"),),
            },
        ),
        migrations.AlterModelOptions(
            name="skillcategory",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (),
                "verbose_name_plural": "Skill Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="timeslottype",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name_plural": "Timeslot Types",
            },
        ),
    ]
