# Generated by Django 5.0.3 on 2024-03-13 16:26

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0009_alter_billingcode_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameworkAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("total_days", models.IntegerField(verbose_name="Total Days")),
                (
                    "allow_over_allocation",
                    models.BooleanField(
                        default=True, verbose_name="Allow Over Allocation"
                    ),
                ),
                (
                    "associated_jobs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="framework",
                        to="jobtracker.job",
                        verbose_name="Associated Jobs",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="framework_agreements",
                        to="jobtracker.client",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "unique_together": {("client", "name")},
            },
        ),
    ]
