# Generated by Django 5.0.6 on 2024-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0009_skill_description_skillcategory_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (0, "No experience"),
                    (1, "Require Support"),
                    (2, "Independent"),
                    (3, "Specialist"),
                ],
                default=0,
            ),
        ),
    ]
