# Generated by Django 5.0.6 on 2024-08-27 10:16

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0011_alter_job_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="description",
            field=django_bleach.models.BleachField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="location",
            field=django_bleach.models.BleachField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="phase",
            name="description",
            field=django_bleach.models.BleachField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="phase",
            name="location",
            field=django_bleach.models.BleachField(blank=True, default="", null=True),
        ),
    ]
