# Generated by Django 5.0.3 on 2024-03-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0011_frameworkagreement_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frameworkagreement",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End Date"),
        ),
    ]
