# Generated by Django 5.0.3 on 2024-03-15 12:09

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import model_utils.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0013_alter_job_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualificationTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="", unique=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.RemoveField(
            model_name="usercertification",
            name="certification",
        ),
        migrations.AlterUniqueTogether(
            name="usercertification",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usercertification",
            name="user",
        ),
        migrations.CreateModel(
            name="Accreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="", unique=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("view_users_accreditations", "View Users with Accreditation"),
                ),
                "unique_together": {("name",)},
            },
        ),
        migrations.CreateModel(
            name="AwardingBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="", unique=True)),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "unique_together": {("name", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="", unique=True)),
                (
                    "validity_period",
                    models.DurationField(
                        blank=True,
                        help_text="How long the qualification is valid for. If left empty, it does not expire.",
                        null=True,
                        verbose_name="Validity Period",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=2000,
                        null=True,
                        verbose_name="Qualification URL",
                    ),
                ),
                (
                    "guidance_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=2000,
                        null=True,
                        verbose_name="Guidance URL",
                    ),
                ),
                (
                    "awarding_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qualifications",
                        to="jobtracker.awardingbody",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        to="jobtracker.qualificationtag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("awarding_body"),
                    django.db.models.functions.text.Lower("name"),
                ],
                "permissions": (
                    ("view_users_qualifications", "View Users with Qualification"),
                ),
                "unique_together": {("name", "slug")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalQualificationRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Revoked"),
                            (3, "Suspended"),
                            (4, "In Progress"),
                            (5, "Pending"),
                            (6, "Attempted"),
                            (7, "Awarded"),
                            (8, "Lapsed"),
                        ],
                        default=0,
                    ),
                ),
                ("last_updated_on", models.DateTimeField(blank=True, editable=False)),
                (
                    "status_changed_date",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status"
                    ),
                ),
                (
                    "awarded_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this qualification was awarded. Validity period will be calculated from this if appropriate.",
                        null=True,
                        verbose_name="Date Awarded",
                    ),
                ),
                (
                    "lapse_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this qualification will lapse. Calculated from the Validity period.",
                        null=True,
                        verbose_name="Date Lapses",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.qualification",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical qualification record",
                "verbose_name_plural": "historical qualification records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="QualificationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Unknown"),
                            (1, "Revoked"),
                            (3, "Suspended"),
                            (4, "In Progress"),
                            (5, "Pending"),
                            (6, "Attempted"),
                            (7, "Awarded"),
                            (8, "Lapsed"),
                        ],
                        default=0,
                    ),
                ),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "status_changed_date",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status"
                    ),
                ),
                (
                    "awarded_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this qualification was awarded. Validity period will be calculated from this if appropriate.",
                        null=True,
                        verbose_name="Date Awarded",
                    ),
                ),
                (
                    "lapse_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this qualification will lapse. Calculated from the Validity period.",
                        null=True,
                        verbose_name="Date Lapses",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="jobtracker.qualification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["qualification", "user"],
            },
        ),
        migrations.DeleteModel(
            name="Certification",
        ),
        migrations.DeleteModel(
            name="UserCertification",
        ),
    ]
