# Generated by Django 5.0.3 on 2024-03-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0014_qualificationtag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="short_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="qualification",
            name="validity_period",
            field=models.DurationField(
                blank=True,
                help_text="How many days the qualification is valid for. If left empty, it does not expire.",
                null=True,
                verbose_name="Validity Period",
            ),
        ),
    ]
