# Generated by Django 5.0.6 on 2024-08-28 11:38

import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import django_fsm
import model_utils.fields
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0015_client_onboarded_users_client_onboarding_required_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                ("id", models.IntegerField(editable=False, verbose_name="Project ID")),
                (
                    "db_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="Database ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (0, "Untracked"),
                            (1, "Pending"),
                            (2, "In Progress"),
                            (3, "Complete"),
                        ],
                        default=0,
                        help_text="Current state of the job",
                        verbose_name="Job Status",
                    ),
                ),
                (
                    "status_changed_date",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status"
                    ),
                ),
                ("is_imported", models.BooleanField(default=False)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Project Title"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "desired_start_date",
                    models.DateField(
                        blank=True,
                        help_text="If left blank, this will be automatically determined from scheduled slots",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "desired_delivery_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="If left blank, this will be automatically determined from scheduled slots",
                        null=True,
                        verbose_name="Delivery date",
                    ),
                ),
                ("overview", django_bleach.models.BleachField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_poc",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Primary Point of Contact",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.organisationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Project",
                "verbose_name_plural": "historical Projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.IntegerField(editable=False, verbose_name="Project ID")),
                (
                    "db_id",
                    models.AutoField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Database ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMIntegerField(
                        choices=[
                            (0, "Untracked"),
                            (1, "Pending"),
                            (2, "In Progress"),
                            (3, "Complete"),
                        ],
                        default=0,
                        help_text="Current state of the job",
                        verbose_name="Job Status",
                    ),
                ),
                (
                    "status_changed_date",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status"
                    ),
                ),
                ("is_imported", models.BooleanField(default=False)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=255,
                        verbose_name="External ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=250, verbose_name="Project Title"),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "desired_start_date",
                    models.DateField(
                        blank=True,
                        help_text="If left blank, this will be automatically determined from scheduled slots",
                        null=True,
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "desired_delivery_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="If left blank, this will be automatically determined from scheduled slots",
                        null=True,
                        verbose_name="Delivery date",
                    ),
                ),
                ("overview", django_bleach.models.BleachField(blank=True, null=True)),
                (
                    "charge_codes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projects",
                        to="jobtracker.billingcode",
                        verbose_name="Charge Code",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "primary_poc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_poc_for",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Primary Point of Contact",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="jobtracker.organisationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="historicaltimeslot",
            name="project",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="jobtracker.project",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeslots",
                to="jobtracker.project",
            ),
        ),
    ]
