# Generated by Django 5.0.3 on 2024-03-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0015_qualification_short_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalqualificationrecord",
            name="attempt_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the attempt.",
                null=True,
                verbose_name="Date of Attempt",
            ),
        ),
        migrations.AddField(
            model_name="qualificationrecord",
            name="attempt_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the attempt.",
                null=True,
                verbose_name="Date of Attempt",
            ),
        ),
        migrations.AlterField(
            model_name="historicalqualificationrecord",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Revoked"),
                    (2, "Suspended"),
                    (3, "In Progress"),
                    (4, "Pending"),
                    (5, "Attempted"),
                    (6, "Awarded"),
                    (7, "Lapsed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="qualificationrecord",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Revoked"),
                    (2, "Suspended"),
                    (3, "In Progress"),
                    (4, "Pending"),
                    (5, "Attempted"),
                    (6, "Awarded"),
                    (7, "Lapsed"),
                ],
                default=0,
            ),
        ),
    ]
