# Generated by Django 5.0.3 on 2024-03-19 15:57

import django.db.models.deletion
import django.db.models.functions.text
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0016_historicalqualificationrecord_attempt_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingcode",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billing_codes",
                to="jobtracker.client",
            ),
        ),
        migrations.AddField(
            model_name="billingcode",
            name="region",
            field=django_countries.fields.CountryField(default="GB", max_length=2),
        ),
        migrations.CreateModel(
            name="BillingCodeAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="associations",
                        to="jobtracker.billingcode",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_codes",
                        to="jobtracker.job",
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("code")],
                "unique_together": {("code", "job")},
            },
        ),
    ]
