# Generated by Django 5.0.6 on 2024-08-28 15:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0017_alter_historicalproject_status_alter_project_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="organisationalunitmember",
            unique_together={("unit", "member")},
        ),
    ]
