# Generated by Django 5.0.3 on 2024-03-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0018_delete_billingcodeassociation"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingcode",
            name="is_internal",
            field=models.BooleanField(default=False),
        ),
    ]
