# Generated by Django 5.0.6 on 2024-08-29 10:57

import chaotica_utils.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0019_alter_job_associated_framework_alter_job_created_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="account_manager",
            field=models.ForeignKey(
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                related_name="jobs_am_for",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Account Manager",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="dep_account_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                related_name="jobs_dam_for",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deputy Account Manager",
            ),
        ),
        migrations.AlterField(
            model_name="jobsupportteamrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                related_name="job_support_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organisationalunitmember",
            name="inviter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                related_name="unitmember_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                related_name="projects_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="primary_poc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET(chaotica_utils.models.get_sentinel_user),
                related_name="projects_poc_for",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Primary Point of Contact",
            ),
        ),
    ]
