# Generated by Django 5.0.6 on 2024-08-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0020_alter_job_account_manager_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                unique=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
