# Generated by Django 5.0.3 on 2024-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0020_jobsupportteamrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsupportteamrole",
            name="billed_hours",
            field=models.FloatField(
                default=0.0,
                help_text="Hours actually billed from the allocated amount",
                verbose_name="Billed Hours",
            ),
        ),
        migrations.AlterField(
            model_name="jobsupportteamrole",
            name="allocated_hours",
            field=models.FloatField(
                default=0.0,
                help_text="Hours allocated to this person",
                verbose_name="Allocated Hours",
            ),
        ),
    ]
