# Generated by Django 5.0.6 on 2024-08-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0021_alter_job_external_id_alter_project_external_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="External ID"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
