# Generated by Django 5.0.3 on 2024-03-22 16:10

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0022_historicaljobsupportteamrole"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["id"],
                "permissions": (
                    ("add_note", "Can Add Note"),
                    ("scope_job", "Can Scope Job"),
                    ("change_schedule", "Can Change Schedule"),
                    ("update_workflow", "Can Update the workflow"),
                    ("assign_poc", "Can assign Point of Contact"),
                    ("assign_framework", "Can assign a framework agreement"),
                ),
                "verbose_name": "Job",
            },
        ),
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("manage_members", "Assign Members"),
                    ("can_view_unit_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("view_job_schedule", "View a Job's Schedule"),
                    ("can_schedule_phases", "Can schedule phases"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    (
                        "can_view_all_leave_requests",
                        "Can view all leave for members of the unit",
                    ),
                    ("can_approve_leave_requests", "Can approve leave requests"),
                ),
            },
        ),
    ]
