# Generated by Django 5.0.3 on 2024-03-22 16:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobtracker", "0023_alter_job_options_alter_organisationalunit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ["id"], "verbose_name": "Job"},
        ),
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("manage_members", "Assign Members"),
                    ("can_view_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    ("can_update_job", "Can update jobs"),
                    ("can_delete_job", "Can delete jobs"),
                    ("can_add_note_job", "Can add a note to jobs"),
                    ("can_assign_poc_job", "Can assign a Point of Contact to jobs"),
                    (
                        "can_manage_framework_job",
                        "Can assign a Point of Contact to jobs",
                    ),
                    ("can_schedule_job", "Can schedule phases"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("view_job_schedule", "View a Job's Schedule"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    (
                        "can_view_all_leave_requests",
                        "Can view all leave for members of the unit",
                    ),
                    ("can_approve_leave_requests", "Can approve leave requests"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="historicalorganisationalunitmember",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Pending Approval"),
                    (1, "Consultant"),
                    (2, "Sales"),
                    (3, "Service Delivery"),
                    (4, "Manager"),
                    (5, "Tech QA'er"),
                    (6, "Pres QA'er"),
                    (7, "Scoper"),
                    (8, "Super Scoper"),
                ],
                default=1,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="organisationalunitmember",
            name="role",
            field=models.IntegerField(
                choices=[
                    (0, "Pending Approval"),
                    (1, "Consultant"),
                    (2, "Sales"),
                    (3, "Service Delivery"),
                    (4, "Manager"),
                    (5, "Tech QA'er"),
                    (6, "Pres QA'er"),
                    (7, "Scoper"),
                    (8, "Super Scoper"),
                ],
                default=1,
                verbose_name="Role",
            ),
        ),
    ]
