# Generated by Django 5.0.6 on 2024-09-05 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0023_alter_historicaljob_external_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlotComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("comment", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to=models.Q(("is_active", True)),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslot_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
