# Generated by Django 5.0.6 on 2024-09-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0024_timeslotcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="external_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, verbose_name="External ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
