# Generated by Django 5.0.6 on 2024-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0025_alter_historicalproject_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
