# Generated by Django 5.0.6 on 2024-09-11 14:42

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0026_alter_historicalproject_external_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": [django.db.models.functions.text.Lower("title")],
                "verbose_name": "Project",
            },
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="External ID",
            ),
        ),
    ]
