# Generated by Django 5.0.6 on 2024-10-09 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0027_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltimeslot",
            name="updated",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timeslot",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
