# Generated by Django 5.0.6 on 2024-10-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0029_alter_organisationalunit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="linkDeliverable",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Typically this is the content delivered to the client.",
                null=True,
                verbose_name="Link to Deliverable",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="linkReportData",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Data used to generate the report such as checklists or evidence.",
                null=True,
                verbose_name="Link to Report Data",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="linkTechData",
            field=models.TextField(
                blank=True,
                default="",
                help_text="All data generated during the job.",
                null=True,
                verbose_name="Link to Technical Data",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="linkDeliverable",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Typically this is the content delivered to the client.",
                null=True,
                verbose_name="Link to Deliverable",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="linkReportData",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Data used to generate the report such as checklists or evidence.",
                null=True,
                verbose_name="Link to Report Data",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="linkTechData",
            field=models.TextField(
                blank=True,
                default="",
                help_text="All data generated during the job.",
                null=True,
                verbose_name="Link to Technical Data",
            ),
        ),
    ]
