# Generated by Django 5.0.6 on 2024-10-28 14:34

import django.utils.timezone
import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0030_alter_historicalphase_linkdeliverable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="last_edited",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="body"
            ),
        ),
        migrations.AddField(
            model_name="historicalfeedback",
            name="last_edited",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="body"
            ),
        ),
    ]
