# Generated by Django 5.0.6 on 2024-11-14 09:38

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0031_feedback_last_edited_historicalfeedback_last_edited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="onboarded_users",
        ),
        migrations.AddField(
            model_name="client",
            name="onboarding_reoccurring_renewal",
            field=models.BooleanField(
                default=False,
                help_text="Requirements must be refreshed repeatably.",
                verbose_name="Reoccurring Renewal Required",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="onboarding_reqs",
            field=models.TextField(
                blank=True,
                help_text="What requirements are there every renewal.",
                null=True,
                verbose_name="Reoccurring Requirements",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="onboarding_reqs_reminder_days",
            field=models.IntegerField(
                default=0,
                help_text="How many days lead should a reminder be sent.",
                verbose_name="Reminder Lead",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="onboarding_reqs_renewal",
            field=models.IntegerField(
                default=0,
                help_text="How many days requirements must be refreshed.",
                verbose_name="Requirements Refresh Every",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="onboarding_reoccurring_renewal",
            field=models.BooleanField(
                default=False,
                help_text="Requirements must be refreshed repeatably.",
                verbose_name="Reoccurring Renewal Required",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="onboarding_reqs",
            field=models.TextField(
                blank=True,
                help_text="What requirements are there every renewal.",
                null=True,
                verbose_name="Reoccurring Requirements",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="onboarding_reqs_reminder_days",
            field=models.IntegerField(
                default=0,
                help_text="How many days lead should a reminder be sent.",
                verbose_name="Reminder Lead",
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="onboarding_reqs_renewal",
            field=models.IntegerField(
                default=0,
                help_text="How many days requirements must be refreshed.",
                verbose_name="Requirements Refresh Every",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="onboarding_required",
            field=models.BooleanField(
                default=False,
                help_text="Only onboarded users can be scheduled on jobs for this client.",
                verbose_name="Onboarding Required",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="onboarding_required",
            field=models.BooleanField(
                default=False,
                help_text="Only onboarded users can be scheduled on jobs for this client.",
                verbose_name="Onboarding Required",
            ),
        ),
        migrations.CreateModel(
            name="Onboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onboarded",
                    models.DateTimeField(
                        blank=True,
                        help_text="This is the date they are considered onboarded",
                        null=True,
                        verbose_name="Date Onboarded",
                    ),
                ),
                (
                    "reqs_completed",
                    models.DateTimeField(
                        blank=True,
                        help_text="This is the date reoccurring requirements were last completed",
                        null=True,
                        verbose_name="Requirements Completed",
                    ),
                ),
                (
                    "offboarded",
                    models.DateTimeField(
                        blank=True,
                        help_text="This is the date they are considered offboarded",
                        null=True,
                        verbose_name="Date Offboarded",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarded_users",
                        to="jobtracker.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarded_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("client"), "user"],
                "unique_together": {("client", "user")},
            },
        ),
    ]
