# Generated by Django 5.0.6 on 2024-11-15 12:31

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0032_remove_client_onboarded_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="onboarding_reqs",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="What requirements are there every renewal.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclient",
            name="onboarding_reqs",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="What requirements are there every renewal.",
                null=True,
            ),
        ),
    ]
