# Generated by Django 5.0.6 on 2024-11-15 13:00

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0033_alter_client_onboarding_reqs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="onboarding_reqs",
        ),
        migrations.RemoveField(
            model_name="historicalclient",
            name="onboarding_reqs",
        ),
        migrations.AddField(
            model_name="client",
            name="onboarding_requirements",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="What requirements are there every renewal.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="onboarding_requirements",
            field=django_bleach.models.BleachField(
                blank=True,
                help_text="What requirements are there every renewal.",
                null=True,
            ),
        ),
    ]
