# Generated by Django 5.0.6 on 2024-11-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0035_alter_client_onboarding_requirements_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="onboarding",
            unique_together=set(),
        ),
    ]
