# Generated by Django 5.0.6 on 2024-11-15 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0036_alter_onboarding_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Onboarding",
            new_name="ClientOnboarding",
        ),
    ]
