# Generated by Django 5.0.6 on 2024-11-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0037_rename_onboarding_clientonboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="validity_period",
            field=models.IntegerField(
                blank=True,
                help_text="How many days the qualification is valid for. If left empty, it does not expire.",
                null=True,
                verbose_name="Validity Period",
            ),
        ),
    ]
