# Generated by Django 5.0.6 on 2024-11-18 16:19

import django.db.models.deletion
import django.db.models.functions.text
import django_bleach.models
import jobtracker.models.team
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0038_alter_qualification_validity_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalqualificationrecord",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Revoked"),
                    (2, "Suspended"),
                    (3, "In Progress"),
                    (4, "Pending"),
                    (5, "Attempted"),
                    (6, "Awarded"),
                    (7, "Unsuccessful"),
                    (8, "Lapsed"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="qualificationrecord",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Unknown"),
                    (1, "Revoked"),
                    (2, "Suspended"),
                    (3, "In Progress"),
                    (4, "Pending"),
                    (5, "Attempted"),
                    (6, "Awarded"),
                    (7, "Unsuccessful"),
                    (8, "Lapsed"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalTeam",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="")),
                (
                    "description",
                    django_bleach.models.BleachField(blank=True, default="", null=True),
                ),
                ("profile_image", models.TextField(blank=True, max_length=100)),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Team is only visible to admins, owners and members",
                        verbose_name="Hidden",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Data"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team",
                "verbose_name_plural": "historical teams",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(default="", unique=True)),
                (
                    "description",
                    django_bleach.models.BleachField(blank=True, default="", null=True),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        upload_to=jobtracker.models.team.get_media_image_file_path,
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Team is only visible to admins, owners and members",
                        verbose_name="Hidden",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="Data"
                    ),
                ),
                (
                    "owners",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users responsible for the management of the team.",
                        limit_choices_to={"is_active": True},
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTeamMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("last_updated_on", models.DateTimeField(blank=True, editable=False)),
                (
                    "joined_at",
                    models.DateField(
                        blank=True,
                        help_text="Date this user joined the group",
                        null=True,
                        verbose_name="Joined",
                    ),
                ),
                (
                    "left_at",
                    models.DateField(
                        blank=True,
                        help_text="Date this user left the group",
                        null=True,
                        verbose_name="Left",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical team member",
                "verbose_name_plural": "historical team members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated_on", models.DateTimeField(auto_now=True)),
                (
                    "joined_at",
                    models.DateField(
                        blank=True,
                        help_text="Date this user joined the group",
                        null=True,
                        verbose_name="Joined",
                    ),
                ),
                (
                    "left_at",
                    models.DateField(
                        blank=True,
                        help_text="Date this user left the group",
                        null=True,
                        verbose_name="Left",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="jobtracker.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["team", "user"],
            },
        ),
    ]
