# Generated by Django 5.0.6 on 2024-11-18 16:32

import jobtracker.models.team
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0039_alter_historicalqualificationrecord_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalteam",
            name="cover_image",
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="cover_image",
            field=models.ImageField(
                blank=True, upload_to=jobtracker.models.team.get_media_image_file_path
            ),
        ),
    ]
