# Generated by Django 5.0.6 on 2024-11-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0040_historicalteam_cover_image_team_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="jobtracker.team",
            ),
        ),
    ]
