# Generated by Django 5.0.6 on 2024-11-18 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0041_alter_teammember_team"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="owners",
            field=models.ManyToManyField(
                help_text="Users responsible for the management of the team.",
                limit_choices_to={"is_active": True},
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
