# Generated by Django 5.0.6 on 2025-02-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0042_alter_team_owners"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphase",
            name="_start_date",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="_start_date",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Start Date",
            ),
        ),
    ]
