# Generated by Django 5.0.6 on 2025-02-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0043_historicalphase__start_date_phase__start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphase",
            name="_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AddField(
            model_name="historicalphase",
            name="_due_to_techqa",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from the end of last day of reporting",
                null=True,
                verbose_name="Due to Tech QA",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="_due_to_techqa",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from the end of last day of reporting",
                null=True,
                verbose_name="Due to Tech QA",
            ),
        ),
    ]
