# Generated by Django 5.0.6 on 2025-02-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0044_historicalphase__delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphase",
            name="_due_to_presqa",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from the end of last day of reporting plus QA days",
                null=True,
                verbose_name="Due to Pres QA",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="_due_to_presqa",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from the end of last day of reporting plus QA days",
                null=True,
                verbose_name="Due to Pres QA",
            ),
        ),
    ]
