# Generated by Django 5.0.6 on 2025-02-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0045_historicalphase__due_to_presqa_phase__due_to_presqa"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="_start_date",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="_start_date",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Start Date",
            ),
        ),
    ]
