# Generated by Django 5.0.6 on 2025-02-10 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0046_historicaljob__delivery_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphase",
            name="was_submitted_late_delivery",
            field=models.BooleanField(
                default=False,
                help_text="Set if the phase was late to Delivery",
                verbose_name="Submitted late to Delivery",
            ),
        ),
        migrations.AddField(
            model_name="historicalphase",
            name="was_submitted_late_pqa",
            field=models.BooleanField(
                default=False,
                help_text="Set if the phase was late to PQA",
                verbose_name="Submitted late to PQA",
            ),
        ),
        migrations.AddField(
            model_name="historicalphase",
            name="was_submitted_late_tqa",
            field=models.BooleanField(
                default=False,
                help_text="Set if the phase was late to TQA",
                verbose_name="Submitted late to TQA",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="was_submitted_late_delivery",
            field=models.BooleanField(
                default=False,
                help_text="Set if the phase was late to Delivery",
                verbose_name="Submitted late to Delivery",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="was_submitted_late_pqa",
            field=models.BooleanField(
                default=False,
                help_text="Set if the phase was late to PQA",
                verbose_name="Submitted late to PQA",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="was_submitted_late_tqa",
            field=models.BooleanField(
                default=False,
                help_text="Set if the phase was late to TQA",
                verbose_name="Submitted late to TQA",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Delivery Date computed from schedule",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date computed from the schedule.",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_completed_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the phase was completed based on state change",
                null=True,
                verbose_name="Actual completed date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_delivery_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the phase actually delivered based on state change.",
                null=True,
                verbose_name="Actual delivered date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_sent_to_pqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the report was sent to PQA based on state change",
                null=True,
                verbose_name="Actual sent to PQA date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_sent_to_tqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the report was sent to TQA based on state change",
                null=True,
                verbose_name="Actual sent to TQA date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="actual_start_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the phase actually started based on state change.",
                null=True,
                verbose_name="Actual start date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="cancellation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the phase was cancelled based on state change",
                null=True,
                verbose_name="Cancelled Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="created_date",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Date the phase record was created",
                verbose_name="Date Created",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="is_imported",
            field=models.BooleanField(
                default=False,
                help_text="If this phase was imported",
                verbose_name="Imported",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="job",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The parent job",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="jobtracker.job",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="last_modified",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the phase was last modified",
                verbose_name="Last Modified",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Who last modified the phase",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="notifications_late_delivery_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late Delivery",
                null=True,
                verbose_name="Late Delivery Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="notifications_late_pqa_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late PQA",
                null=True,
                verbose_name="Late PQA Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="notifications_late_tqa_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late TQA",
                null=True,
                verbose_name="Late TQA Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="notifications_workflow_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Workflow",
                null=True,
                verbose_name="Workflow Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="pre_checks_done_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the pre-checks were completed based on state change",
                null=True,
                verbose_name="Pre-checks Completed Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="service",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Associated service to be delivered from this Phase",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="jobtracker.service",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="Delivery Date computed from schedule",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date computed from the schedule.",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_completed_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the phase was completed based on state change",
                null=True,
                verbose_name="Actual completed date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_delivery_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the phase actually delivered based on state change.",
                null=True,
                verbose_name="Actual delivered date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_sent_to_pqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the report was sent to PQA based on state change",
                null=True,
                verbose_name="Actual sent to PQA date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_sent_to_tqa_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the report was sent to TQA based on state change",
                null=True,
                verbose_name="Actual sent to TQA date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="actual_start_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Date the phase actually started based on state change.",
                null=True,
                verbose_name="Actual start date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="cancellation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the phase was cancelled based on state change",
                null=True,
                verbose_name="Cancelled Date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date the phase record was created",
                verbose_name="Date Created",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="is_imported",
            field=models.BooleanField(
                default=False,
                help_text="If this phase was imported",
                verbose_name="Imported",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="job",
            field=models.ForeignKey(
                help_text="The parent job",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phases",
                to="jobtracker.job",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="last_modified",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the phase was last modified",
                verbose_name="Last Modified",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who last modified the phase",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="notifications_late_delivery_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late Delivery",
                null=True,
                verbose_name="Late Delivery Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="notifications_late_pqa_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late PQA",
                null=True,
                verbose_name="Late PQA Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="notifications_late_tqa_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late TQA",
                null=True,
                verbose_name="Late TQA Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="notifications_workflow_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Workflow",
                null=True,
                verbose_name="Workflow Notification last sent",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="pre_checks_done_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When the pre-checks were completed based on state change",
                null=True,
                verbose_name="Pre-checks Completed Date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated service to be delivered from this Phase",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="phases",
                to="jobtracker.service",
            ),
        ),
    ]
