# Generated by Django 5.0.6 on 2025-03-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0047_historicalphase_was_submitted_late_delivery_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorganisationalunit",
            name="businessHours_lunch_endTime",
            field=models.TimeField(default="13:00:00", verbose_name="Lunch End Time"),
        ),
        migrations.AddField(
            model_name="historicalorganisationalunit",
            name="businessHours_lunch_startTime",
            field=models.TimeField(default="12:00:00", verbose_name="Lunch Start Time"),
        ),
        migrations.AddField(
            model_name="organisationalunit",
            name="businessHours_lunch_endTime",
            field=models.TimeField(default="13:00:00", verbose_name="Lunch End Time"),
        ),
        migrations.AddField(
            model_name="organisationalunit",
            name="businessHours_lunch_startTime",
            field=models.TimeField(default="12:00:00", verbose_name="Lunch Start Time"),
        ),
    ]
