# Generated by Django 5.0.6 on 2025-03-17 17:17

import jobtracker.models.orgunit
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0048_historicalorganisationalunit_businesshours_lunch_endtime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalorganisationalunit",
            name="businessHours_days",
            field=models.JSONField(
                blank=True,
                default=jobtracker.models.orgunit._default_business_days,
                help_text="An int array with the numbers equaling the day of the week. Sunday == 0, Monday == 1 etc",
                null=True,
                verbose_name="Days",
            ),
        ),
        migrations.AlterField(
            model_name="organisationalunit",
            name="businessHours_days",
            field=models.JSONField(
                blank=True,
                default=jobtracker.models.orgunit._default_business_days,
                help_text="An int array with the numbers equaling the day of the week. Sunday == 0, Monday == 1 etc",
                null=True,
                verbose_name="Days",
            ),
        ),
    ]
