# Generated by Django 5.0.6 on 2025-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0049_alter_historicalorganisationalunit_businesshours_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalphase",
            name="notifications_prechecks_late_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late Prechecks",
                null=True,
                verbose_name="Late Prechecks Notification last sent",
            ),
        ),
        migrations.AddField(
            model_name="phase",
            name="notifications_prechecks_late_last_fired",
            field=models.DateTimeField(
                blank=True,
                help_text="Date the last notification was sent for Late Prechecks",
                null=True,
                verbose_name="Late Prechecks Notification last sent",
            ),
        ),
    ]
