# Generated by Django 5.0.6 on 2025-04-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0050_historicalphase_notifications_prechecks_late_last_fired_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="desired_start_date",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Desired Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="desired_start_date",
            field=models.DateField(
                blank=True,
                help_text="If left blank, this will be automatically determined from scheduled slots",
                null=True,
                verbose_name="Desired Start Date",
            ),
        ),
    ]
