# Generated by Django 5.2.3 on 2025-09-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0052_alter_organisationalunit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="desired_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If set, will override scheduled dates",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="desired_start_date",
            field=models.DateField(
                blank=True,
                help_text="If set, will override scheduled dates",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Optional: External reference ID",
                max_length=255,
                null=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Optional: Cost of the job to the client",
                max_digits=10,
                null=True,
                verbose_name="Sales Revenue",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="desired_delivery_date",
            field=models.DateField(
                blank=True,
                db_index=True,
                help_text="If set, will override scheduled dates",
                null=True,
                verbose_name="Delivery date",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="desired_start_date",
            field=models.DateField(
                blank=True,
                help_text="If set, will override scheduled dates",
                null=True,
                verbose_name="Start Date",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Optional: External reference ID",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="External ID",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="revenue",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Optional: Cost of the job to the client",
                max_digits=10,
                null=True,
                verbose_name="Sales Revenue",
            ),
        ),
    ]
