# Generated by Django 5.2.3 on 2025-09-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0053_alter_historicaljob_desired_delivery_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalservice",
            name="is_core",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this service is considered critical",
                verbose_name="Is Core Service",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="is_core",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this service is considered critical",
                verbose_name="Is Core Service",
            ),
        ),
    ]
