# Generated by Django 5.2.3 on 2025-09-16 15:44

import django_bleach.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0054_historicalservice_is_core_service_is_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalphase",
            name="comm_reqs",
            field=django_bleach.models.BleachField(
                blank=True, null=True, verbose_name="Communication Requirements"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="location",
            field=django_bleach.models.BleachField(
                blank=True, default="", null=True, verbose_name="Onsite Location"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="prerequisites",
            field=django_bleach.models.BleachField(
                blank=True, null=True, verbose_name="Pre-requisites"
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="restrictions",
            field=django_bleach.models.BleachField(
                blank=True,
                null=True,
                verbose_name="Time restrictions / Special requirements",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="scheduling_requirements",
            field=django_bleach.models.BleachField(
                blank=True,
                null=True,
                verbose_name="Special requirements for scheduling",
            ),
        ),
        migrations.AlterField(
            model_name="historicalphase",
            name="test_target",
            field=django_bleach.models.BleachField(
                blank=True, null=True, verbose_name="Test Target URL/IPs/Scope"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="comm_reqs",
            field=django_bleach.models.BleachField(
                blank=True, null=True, verbose_name="Communication Requirements"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="location",
            field=django_bleach.models.BleachField(
                blank=True, default="", null=True, verbose_name="Onsite Location"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="prerequisites",
            field=django_bleach.models.BleachField(
                blank=True, null=True, verbose_name="Pre-requisites"
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="restrictions",
            field=django_bleach.models.BleachField(
                blank=True,
                null=True,
                verbose_name="Time restrictions / Special requirements",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="scheduling_requirements",
            field=django_bleach.models.BleachField(
                blank=True,
                null=True,
                verbose_name="Special requirements for scheduling",
            ),
        ),
        migrations.AlterField(
            model_name="phase",
            name="test_target",
            field=django_bleach.models.BleachField(
                blank=True, null=True, verbose_name="Test Target URL/IPs/Scope"
            ),
        ),
    ]
