# Generated by Django 5.2.3 on 2025-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0055_alter_historicalphase_comm_reqs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills that should be learned before this one",
                related_name="dependent_skills",
                to="jobtracker.skill",
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="related_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills that are commonly used together",
                to="jobtracker.skill",
            ),
        ),
    ]
