# Generated by Django 5.2.12 on 2026-03-16 15:18

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0059_add_business_hours_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awardingbody",
            options={
                "ordering": [django.db.models.functions.text.Lower("name")],
                "verbose_name_plural": "Awarding bodies",
            },
        ),
        migrations.AddField(
            model_name="awardingbody",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="awardingbody",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="awarding_bodies/"
            ),
        ),
        migrations.AddField(
            model_name="awardingbody",
            name="url",
            field=models.URLField(
                blank=True, max_length=2000, null=True, verbose_name="Website URL"
            ),
        ),
        migrations.AddField(
            model_name="historicalqualificationrecord",
            name="certificate_file",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="historicalqualificationrecord",
            name="certificate_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Certificate/Registration Number",
            ),
        ),
        migrations.AddField(
            model_name="historicalqualificationrecord",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="qualification",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="qualificationrecord",
            name="certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/"),
        ),
        migrations.AddField(
            model_name="qualificationrecord",
            name="certificate_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Certificate/Registration Number",
            ),
        ),
        migrations.AddField(
            model_name="qualificationrecord",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
