# Generated by Django 5.2.12 on 2026-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0061_historicalqualificationrecord_verified_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="verification_required",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, awarded records require manager verification.",
                verbose_name="Manager Verification Required",
            ),
        ),
    ]
