# Generated by Django 5.2.12 on 2026-07-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0064_alter_organisationalunit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phase",
            name="links",
            field=models.ManyToManyField(
                blank=True, related_name="phases", to="jobtracker.link"
            ),
        ),
    ]
