# Generated by Django 5.2.12 on 2026-07-04 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0065_phase_links_m2m"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="linkType",
            field=models.IntegerField(
                choices=[
                    (0, "Other"),
                    (1, "SharePoint"),
                    (2, "Teams"),
                    (3, "Previous Job/Phase"),
                    (4, "Related"),
                    (5, "Scoping"),
                ],
                default=0,
                help_text="Type of link",
                verbose_name="Link Type",
            ),
        ),
        migrations.CreateModel(
            name="ScheduleAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("MOVE", "Move"),
                            ("CLEAR", "Clear"),
                            ("BATCH", "Batch"),
                            ("REVERT", "Revert"),
                        ],
                        max_length=16,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(default=list)),
                ("reverted", models.BooleanField(default=False)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_actions",
                        to="jobtracker.job",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_actions",
                        to="jobtracker.phase",
                    ),
                ),
                (
                    "reverted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reverts",
                        to="jobtracker.scheduleaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "permissions": [
                    ("revert_any_scheduleaction", "Can revert any schedule change")
                ],
            },
        ),
    ]
