# Generated by Django 5.2.12 on 2026-07-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0066_alter_link_linktype_scheduleaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='qualificationsDesired',
            field=models.ManyToManyField(blank=True, help_text='Qualifications desired but not essential', related_name='services_qual_desired', to='jobtracker.qualification'),
        ),
        migrations.AddField(
            model_name='service',
            name='qualificationsRequired',
            field=models.ManyToManyField(blank=True, help_text='Qualifications required to perform this service', related_name='services_qual_required', to='jobtracker.qualification'),
        ),
    ]
