# Generated by Django 5.2.12 on 2026-07-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0067_service_qualificationsdesired_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="demonstrated_skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills this qualification evidences proficiency in",
                related_name="qualifications",
                to="jobtracker.skill",
                verbose_name="Skills Demonstrated",
            ),
        ),
    ]
