# Generated by Django 5.2.12 on 2026-07-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0068_qualification_demonstrated_skills"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Accreditation",
        ),
    ]
