# Generated by Django 5.2.12 on 2026-07-16 15:50

from django.conf import settings
from django.db import migrations, models


def copy_lead_to_leads(apps, schema_editor):
    """Preserve the existing single lead by copying it into the new M2M."""
    OrganisationalUnit = apps.get_model("jobtracker", "OrganisationalUnit")
    for unit in OrganisationalUnit.objects.exclude(lead__isnull=True):
        unit.leads.add(unit.lead_id)


def copy_leads_to_lead(apps, schema_editor):
    """Reverse: fold the first lead back into the single FK."""
    OrganisationalUnit = apps.get_model("jobtracker", "OrganisationalUnit")
    for unit in OrganisationalUnit.objects.all():
        first_lead = unit.leads.first()
        if first_lead is not None:
            unit.lead = first_lead
            unit.save(update_fields=["lead"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0070_fix_tqa_pqa_scoper_superscoper_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organisationalunit",
            name="leads",
            field=models.ManyToManyField(
                blank=True, related_name="units_lead", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(copy_lead_to_leads, copy_leads_to_lead),
        migrations.RemoveField(
            model_name="historicalorganisationalunit",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="organisationalunit",
            name="lead",
        ),
    ]
