# Generated by Django 5.2.12 on 2026-07-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0071_remove_historicalorganisationalunit_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='external_url',
            field=models.URLField(blank=True, default=None, help_text='Link back to the source system this project was imported from (e.g. RM).', max_length=500, null=True, verbose_name='External URL'),
        ),
        migrations.AddField(
            model_name='project',
            name='external_url',
            field=models.URLField(blank=True, default=None, help_text='Link back to the source system this project was imported from (e.g. RM).', max_length=500, null=True, verbose_name='External URL'),
        ),
    ]
