# Generated by Django 5.2.12 on 2026-07-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0072_historicalproject_external_url_project_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional client this project is associated with.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='jobtracker.client'),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional client this project is associated with.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='jobtracker.client'),
        ),
    ]
