# Generated by Django 5.2.12 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0073_historicalproject_client_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='deliverable',
            field=models.BooleanField(default=False, help_text='This is client-deliverable work — confirmed deliverable time counts toward utilisation.'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='state',
            field=models.IntegerField(choices=[(0, 'Internal'), (1, 'Tentative'), (2, 'Confirmed')], default=0, help_text='Commercial certainty (mirrors RM). Confirmed + deliverable counts toward utilisation.', verbose_name='Project State'),
        ),
        migrations.AddField(
            model_name='project',
            name='deliverable',
            field=models.BooleanField(default=False, help_text='This is client-deliverable work — confirmed deliverable time counts toward utilisation.'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, 'Internal'), (1, 'Tentative'), (2, 'Confirmed')], default=0, help_text='Commercial certainty (mirrors RM). Confirmed + deliverable counts toward utilisation.', verbose_name='Project State'),
        ),
    ]
