# Generated by Django 5.2.12 on 2026-08-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0074_historicalproject_deliverable_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalorganisationalunit",
            name="approval_required",
        ),
        migrations.RemoveField(
            model_name="organisationalunit",
            name="approval_required",
        ),
    ]
