# Generated by Django 5.2.12 on 2026-08-05 12:27

import django.db.models.functions.text
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0076_cleanup_phases_of_deleted_jobs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("assign_account_managers_client", "Assign Account Managers"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("manage_members", "Assign Members"),
                    ("can_view_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    ("can_update_job", "Can update jobs"),
                    (
                        "can_refire_notifications_job",
                        "Can refire notifications for jobs",
                    ),
                    ("can_delete_job", "Can delete jobs"),
                    ("can_add_note_job", "Can add a note to jobs"),
                    ("can_assign_poc_job", "Can assign a Point of Contact to jobs"),
                    ("can_manage_framework_job", "Can assign a framework to jobs"),
                    ("can_add_phases", "Can add phases"),
                    ("can_delete_phases", "Can add phases"),
                    ("can_schedule_job", "Can schedule phases"),
                    ("can_deliver_job", "Can deliver a job"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("view_job_schedule", "View a Job's Schedule"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    ("can_deliver_jobs", "Can Deliver jobs"),
                    ("can_conduct_review", "Can conduct reviews"),
                    ("can_view_all_reviews", "Can view all reviews"),
                    ("notification_pool_scoping", "Scoping Pool"),
                    ("notification_pool_scheduling", "Scheduling Pool"),
                    ("notification_pool_tqa", "TQA Pool"),
                    ("notification_pool_pqa", "PQA Pool"),
                    (
                        "can_view_all_leave_requests",
                        "Can view all leave for members of the unit",
                    ),
                    ("can_approve_leave_requests", "Can approve leave requests"),
                ),
            },
        ),
        migrations.AlterModelManagers(
            name="client",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organisationalunit",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="client",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalclient",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalorganisationalunit",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalorganisationalunit",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="organisationalunit",
            name="deleted_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organisationalunit",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
