# Generated by Django 5.2.12 on 2026-08-07 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Legacy auto-generated M2M through-tables for Job.charge_codes /
# Project.charge_codes. They are dropped by the RemoveField operations at the
# end of this migration, so the copy/uncopy RunPython must read/write them by
# raw table name while they still exist.
_JOB_M2M = "jobtracker_job_charge_codes"
_PROJECT_M2M = "jobtracker_project_charge_codes"


def copy_m2m_to_assignments(apps, schema_editor):
    """Copy existing job/project charge-code M2M rows into undated assignments."""
    BillingCodeAssignment = apps.get_model("jobtracker", "BillingCodeAssignment")
    connection = schema_editor.connection

    rows = []
    with connection.cursor() as cursor:
        cursor.execute(f"SELECT job_id, billingcode_id FROM {_JOB_M2M}")
        for job_id, code_id in cursor.fetchall():
            rows.append(
                BillingCodeAssignment(job_id=job_id, code_id=code_id)
            )
        cursor.execute(f"SELECT project_id, billingcode_id FROM {_PROJECT_M2M}")
        for project_id, code_id in cursor.fetchall():
            rows.append(
                BillingCodeAssignment(project_id=project_id, code_id=code_id)
            )

    if rows:
        BillingCodeAssignment.objects.bulk_create(rows, batch_size=500)


def copy_assignments_to_m2m(apps, schema_editor):
    """Reverse: copy undated job/project assignments back into the M2M tables."""
    BillingCodeAssignment = apps.get_model("jobtracker", "BillingCodeAssignment")
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        for a in BillingCodeAssignment.objects.filter(
            job__isnull=False, start_date__isnull=True, end_date__isnull=True
        ):
            cursor.execute(
                f"INSERT INTO {_JOB_M2M} (job_id, billingcode_id) VALUES (%s, %s)",
                [a.job_id, a.code_id],
            )
        for a in BillingCodeAssignment.objects.filter(
            project__isnull=False, start_date__isnull=True, end_date__isnull=True
        ):
            cursor.execute(
                f"INSERT INTO {_PROJECT_M2M} (project_id, billingcode_id) VALUES (%s, %s)",
                [a.project_id, a.code_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0077_alter_client_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCodeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobtracker.billingcode')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_code_assignments', to='jobtracker.job')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_code_assignments', to='jobtracker.phase')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_code_assignments', to='jobtracker.project')),
            ],
            options={
                'indexes': [models.Index(fields=['job'], name='jobtracker__job_id_7e9c19_idx'), models.Index(fields=['phase'], name='jobtracker__phase_i_9dc2cd_idx'), models.Index(fields=['project'], name='jobtracker__project_ca8d33_idx'), models.Index(fields=['code'], name='jobtracker__code_id_ce7619_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('job__isnull', False), ('phase__isnull', True), ('project__isnull', True)), models.Q(('job__isnull', True), ('phase__isnull', False), ('project__isnull', True)), models.Q(('job__isnull', True), ('phase__isnull', True), ('project__isnull', False)), _connector='OR'), name='billingcodeassignment_exactly_one_target'), models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='billingcodeassignment_valid_date_range'), models.UniqueConstraint(fields=('code', 'job', 'phase', 'project', 'start_date', 'end_date'), name='billingcodeassignment_unique_target_range')],
            },
        ),
        migrations.RunPython(copy_m2m_to_assignments, copy_assignments_to_m2m),
        migrations.RemoveField(
            model_name='job',
            name='charge_codes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='charge_codes',
        ),
    ]
