# Generated by Django 5.2.12 on 2026-09-09 10:09

import chaotica_utils.utils.common
import django.db.models.deletion
import django.db.models.functions.text
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def grant_loaded_cost_perm(apps, schema_editor):
    """Grant the new ``can_view_loaded_costs`` permission to manager roles.

    Custom permissions are created in a post_migrate signal *after* this
    migration runs, so the row won't exist yet — create it explicitly (keyed to
    the OrganisationalUnit content type) and add it to every management role.
    Existing members inherit it on the next ``sync_permissions`` (membership
    save / admin resync). No-op on a fresh build (no roles yet).
    """
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    OrganisationalUnit = apps.get_model("jobtracker", "OrganisationalUnit")
    OrganisationalUnitRole = apps.get_model("jobtracker", "OrganisationalUnitRole")

    ct = ContentType.objects.get_for_model(OrganisationalUnit)
    perm, _ = Permission.objects.get_or_create(
        codename="can_view_loaded_costs",
        content_type=ct,
        defaults={"name": "Can view loaded cost rates"},
    )
    for role in OrganisationalUnitRole.objects.filter(manage_role=True):
        role.permissions.add(perm)


def revoke_loaded_cost_perm(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")

    OrganisationalUnitRole = apps.get_model("jobtracker", "OrganisationalUnitRole")
    perm = Permission.objects.filter(codename="can_view_loaded_costs").first()
    if perm is None:
        return
    for role in OrganisationalUnitRole.objects.filter(manage_role=True):
        role.permissions.remove(perm)


class Migration(migrations.Migration):

    dependencies = [
        (
            "jobtracker",
            "0078_remove_job_charge_codes_remove_project_charge_codes_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationalunit",
            options={
                "base_manager_name": "all_objects",
                "default_manager_name": "objects",
                "ordering": [django.db.models.functions.text.Lower("name")],
                "permissions": (
                    ("manage_members", "Assign Members"),
                    ("can_view_jobs", "Can view jobs"),
                    ("can_add_job", "Can add jobs"),
                    ("can_update_job", "Can update jobs"),
                    (
                        "can_refire_notifications_job",
                        "Can refire notifications for jobs",
                    ),
                    ("can_delete_job", "Can delete jobs"),
                    ("can_add_note_job", "Can add a note to jobs"),
                    ("can_assign_poc_job", "Can assign a Point of Contact to jobs"),
                    ("can_manage_framework_job", "Can assign a framework to jobs"),
                    ("can_add_phases", "Can add phases"),
                    ("can_delete_phases", "Can add phases"),
                    ("can_schedule_job", "Can schedule phases"),
                    ("can_deliver_job", "Can deliver a job"),
                    ("view_users_schedule", "View Members Schedule"),
                    ("view_job_schedule", "View a Job's Schedule"),
                    ("can_scope_jobs", "Can scope jobs"),
                    ("can_signoff_scopes", "Can signoff scopes"),
                    ("can_signoff_own_scopes", "Can signoff own scopes"),
                    ("can_tqa_jobs", "Can TQA jobs"),
                    ("can_pqa_jobs", "Can PQA jobs"),
                    ("can_deliver_jobs", "Can Deliver jobs"),
                    ("can_conduct_review", "Can conduct reviews"),
                    ("can_view_all_reviews", "Can view all reviews"),
                    ("notification_pool_scoping", "Scoping Pool"),
                    ("notification_pool_scheduling", "Scheduling Pool"),
                    ("notification_pool_tqa", "TQA Pool"),
                    ("notification_pool_pqa", "PQA Pool"),
                    (
                        "can_view_all_leave_requests",
                        "Can view all leave for members of the unit",
                    ),
                    ("can_approve_leave_requests", "Can approve leave requests"),
                    ("can_view_loaded_costs", "Can view loaded cost rates"),
                ),
            },
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="support_premium_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-job override of the support pool premium %. Blank = unit/global default.",
                max_digits=5,
                null=True,
                verbose_name="Support Premium Override (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicaljobsupportteamrole",
            name="is_overridden",
            field=models.BooleanField(
                default=False,
                help_text="Set when this row is manually edited, so re-applying the unit support template leaves it untouched.",
            ),
        ),
        migrations.AddField(
            model_name="historicaljobsupportteamrole",
            name="profile_weight",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0"),
                help_text="Coverage weight (1.0 = 100%). Drives this person's share of the support pool.",
                max_digits=5,
                verbose_name="Profile Weight",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganisationalunit",
            name="support_premium_default",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8"),
                help_text="Default % of a job's revenue reserved for the support-team pool.",
                max_digits=5,
                verbose_name="Support Premium Default (%)",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="support_premium_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-job override of the support pool premium %. Blank = unit/global default.",
                max_digits=5,
                null=True,
                verbose_name="Support Premium Override (%)",
            ),
        ),
        migrations.AddField(
            model_name="jobsupportteamrole",
            name="is_overridden",
            field=models.BooleanField(
                default=False,
                help_text="Set when this row is manually edited, so re-applying the unit support template leaves it untouched.",
            ),
        ),
        migrations.AddField(
            model_name="jobsupportteamrole",
            name="profile_weight",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0"),
                help_text="Coverage weight (1.0 = 100%). Drives this person's share of the support pool.",
                max_digits=5,
                verbose_name="Profile Weight",
            ),
        ),
        migrations.AddField(
            model_name="organisationalunit",
            name="support_premium_default",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8"),
                help_text="Default % of a job's revenue reserved for the support-team pool.",
                max_digits=5,
                verbose_name="Support Premium Default (%)",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalOrganisationalUnitSupportTemplateMember",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "Commercial"),
                            (1, "QA"),
                            (2, "Scope"),
                        ],
                        default=0,
                        verbose_name="Role",
                    ),
                ),
                (
                    "profile_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0"),
                        help_text="Coverage weight (1.0 = 100%). Drives this person's share of the support pool.",
                        max_digits=5,
                        verbose_name="Profile Weight",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.organisationalunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical organisational unit support template member",
                "verbose_name_plural": "historical organisational unit support template members",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSupportBudgetDraw",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                (
                    "hours_drawn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours cashed out for this period.",
                        max_digits=8,
                        verbose_name="Hours Drawn",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_role",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobtracker.jobsupportteamrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Denormalised from support_role.user for fast per-user queries.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical support budget draw",
                "verbose_name_plural": "historical support budget draws",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OrganisationalUnitSupportTemplateMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "Commercial"),
                            (1, "QA"),
                            (2, "Scope"),
                        ],
                        default=0,
                        verbose_name="Role",
                    ),
                ),
                (
                    "profile_weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1.0"),
                        help_text="Coverage weight (1.0 = 100%). Drives this person's share of the support pool.",
                        max_digits=5,
                        verbose_name="Profile Weight",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_template",
                        to="jobtracker.organisationalunit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        related_name="support_template_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
                "unique_together": {("unit", "user")},
            },
        ),
        migrations.CreateModel(
            name="SupportBudgetDraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Period Start")),
                ("period_end", models.DateField(verbose_name="Period End")),
                (
                    "hours_drawn",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hours cashed out for this period.",
                        max_digits=8,
                        verbose_name="Hours Drawn",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draws",
                        to="jobtracker.jobsupportteamrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Denormalised from support_role.user for fast per-user queries.",
                        null=True,
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        related_name="support_budget_draws",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["user", "period_start"],
                        name="jobtracker__user_id_234059_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(grant_loaded_cost_perm, revoke_loaded_cost_perm),
    ]
