# Generated by Django 5.2.12 on 2026-09-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobtracker", "0080_support_profile_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljobsupportteamrole",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Other"), (3, "Commercial"), (1, "QA"), (2, "Scope")],
                default=0,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="historicalorganisationalunitsupporttemplatemember",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Other"), (3, "Commercial"), (1, "QA"), (2, "Scope")],
                default=0,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="jobsupportteamrole",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Other"), (3, "Commercial"), (1, "QA"), (2, "Scope")],
                default=0,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="organisationalunitsupporttemplatemember",
            name="role",
            field=models.IntegerField(
                choices=[(0, "Other"), (3, "Commercial"), (1, "QA"), (2, "Scope")],
                default=0,
                verbose_name="Role",
            ),
        ),
    ]
