# Generated by Django 5.0.6 on 2025-03-06 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PetPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pet_name", models.CharField(default="Bitsy", max_length=50)),
                (
                    "pet_position",
                    models.CharField(
                        choices=[
                            ("bottom-right", "Bottom Right"),
                            ("bottom-left", "Bottom Left"),
                            ("top-right", "Top Right"),
                            ("top-left", "Top Left"),
                        ],
                        default="bottom-right",
                        max_length=20,
                    ),
                ),
                (
                    "pet_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
