# Generated by Django 5.0.6 on 2025-03-07 10:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("virtualpet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamPetEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="petpreference",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petpreference",
            name="current_energy",
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name="petpreference",
            name="current_happiness",
            field=models.FloatField(default=80),
        ),
        migrations.AddField(
            model_name="petpreference",
            name="last_fed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="petpreference",
            name="last_interaction",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="petpreference",
            name="last_state",
            field=models.CharField(default="idle", max_length=20),
        ),
        migrations.AddField(
            model_name="petpreference",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PetStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_feeds", models.IntegerField(default=0)),
                ("total_plays", models.IntegerField(default=0)),
                ("total_pets", models.IntegerField(default=0)),
                ("total_sleeps", models.IntegerField(default=0)),
                ("longest_happiness_streak", models.IntegerField(default=0)),
                ("current_happiness_streak", models.IntegerField(default=0)),
                ("highest_happiness", models.FloatField(default=80)),
                ("lowest_happiness", models.FloatField(default=80)),
                ("average_happiness", models.FloatField(default=80)),
                ("phase_completions", models.IntegerField(default=0)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "pet_preference",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="virtualpet.petpreference",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Pet Statistics",
            },
        ),
        migrations.CreateModel(
            name="PetAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("achievement_id", models.CharField(max_length=50)),
                ("achievement_name", models.CharField(max_length=100)),
                (
                    "unlocked_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "pet_preference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="virtualpet.petpreference",
                    ),
                ),
            ],
            options={
                "unique_together": {("pet_preference", "achievement_id")},
            },
        ),
    ]
