"""Generate synthetic billing-code + support-team test data over the last N months.

Decorates *existing* scheduled jobs (it does not create jobs/clients): a variety
of WBS/billing codes (client-level & reused, job-level, phase overrides, dated,
internal WBS), derived job revenue, the support-team template applied to jobs
whose unit already has one, backdated loaded cost rates, and some draw-downs.

Idempotent (deterministic ``get_or_create`` keys). ``--clear`` removes only what
this command generated (tracked via a marker user + deterministic code strings).

Dev-only: refuses to run when ``DEBUG=False`` unless ``--force`` is given.
"""

import random
from contextlib import contextmanager
from datetime import timedelta
from decimal import Decimal

from django.apps import apps
from django.conf import settings
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.db.models.signals import m2m_changed, post_save, pre_delete, pre_save
from django.utils import timezone

from chaotica_utils.models import User, UserCost, get_sentinel_user
from chaotica_utils.utils import period_for_date, previous_period
from chaotica_utils.utils.support_budget import build_job_support_budget
from jobtracker.enums import DefaultTimeSlotTypes, JobStatuses
from jobtracker.models import (
    BillingCode,
    BillingCodeAssignment,
    Job,
    JobSupportTeamRole,
    SupportBudgetDraw,
    TimeSlot,
)

@contextmanager
def _audit_muted():
    """Temporarily disconnect the finance/config audit signals.

    Bulk synthetic data shouldn't spam AuditEvents, and on a utf8 (non-utf8mb4)
    DB an audited save whose message contains a 4-byte char (e.g. an emoji in a
    user's name) raises OperationalError 1366 and poisons the transaction.
    Reconnected on exit via the idempotent ``connect_audit_signals``."""
    from chaotica_utils import signals as sig

    for (app_label, model_name), _cat in sig._AUDITED_MODELS.items():
        try:
            model = apps.get_model(app_label, model_name)
        except LookupError:
            continue
        uid = "audit_{}_{}".format(app_label, model_name)
        pre_save.disconnect(sender=model, dispatch_uid=uid + "_presave")
        post_save.disconnect(sender=model, dispatch_uid=uid + "_postsave")
        pre_delete.disconnect(sender=model, dispatch_uid=uid + "_predelete")
    for (app_label, model_name, field_name), _cat in sig._AUDITED_M2M.items():
        try:
            model = apps.get_model(app_label, model_name)
        except LookupError:
            continue
        through = getattr(model, field_name).through
        m2m_changed.disconnect(
            sender=through,
            dispatch_uid="audit_m2m_{}_{}_{}".format(app_label, model_name, field_name),
        )
    try:
        yield
    finally:
        sig.connect_audit_signals()


# Internal / WBS codes (client-less). Varied formats on purpose.
INTERNAL_WBS_CODES = [
    "WBS.OVERHEAD.001",
    "INT-BENCH",
    "WBS.L-AND-D.002",
    "PRJ-INTERNAL-2026",
]


class Command(BaseCommand):
    help = (
        "Populate existing 6-month-scheduled jobs with a variety of billing codes, "
        "derived revenue, the support-team template (template-owning units only), "
        "backdated LCRs and some draw-downs. Idempotent; supports --clear."
    )

    def add_arguments(self, parser):
        parser.add_argument("--months", type=int, default=6)
        parser.add_argument("--day-rate", type=Decimal, default=Decimal("1200"))
        parser.add_argument("--draws", type=int, default=40)
        parser.add_argument(
            "--force",
            action="store_true",
            help="Required to run when DEBUG=False.",
        )
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Remove data generated by this command (codes/assignments/draws) and exit.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        if not settings.DEBUG and not options["force"]:
            raise CommandError(
                "Refusing to run with DEBUG=False. Pass --force if you really mean it."
            )

        self.counts = {
            "codes": 0,
            "assignments": 0,
            "jobs_revenued": 0,
            "lcr_backdated": 0,
            "lcr_created": 0,
            "support_applied": 0,
            "draws": 0,
        }
        # Provenance/cleanup tag. Reuse the existing sentinel "system" user
        # rather than creating a new one — creating a User fires the audit signal,
        # which on a utf8 (non-utf8mb4) DB chokes on the emoji in its message.
        self.marker = get_sentinel_user()
        self.window_start = timezone.now().date() - timedelta(days=30 * options["months"])
        self.day_rate = options["day_rate"]

        with _audit_muted():
            if options["clear"]:
                self._clear()
                self._report(cleared=True)
                return

            self.stdout.write(
                self.style.SUCCESS(
                    "Generating billing/support test data from {} onwards...".format(
                        self.window_start
                    )
                )
            )

            self._backdate_lcrs()

            jobs = list(
                Job.objects.filter(
                    phases__timeslots__start__date__gte=self.window_start
                )
                .exclude(status__in=[JobStatuses.DELETED, JobStatuses.ARCHIVED])
                .distinct()
                .select_related("client", "unit")
                .prefetch_related("phases")
            )
            self.stdout.write("  {} jobs scheduled in the window.".format(len(jobs)))

            for i, job in enumerate(jobs):
                self._codes_for_job(i, job)
                self._set_revenue(job)
                self._apply_support(job)

            self._seed_draws(jobs, options["draws"])
            self._report()

    # -- LCR -----------------------------------------------------------------

    def _backdate_lcrs(self):
        """Move each user's earliest cost row back to the window start so
        ``UserCost.cost_on`` resolves for historical job dates. Moving the *min*
        earlier can't collide with unique_together (user, effective_from)."""
        for user in User.objects.filter(costs__isnull=False).distinct():
            earliest = user.costs.order_by("effective_from", "pk").first()
            if earliest and (
                earliest.effective_from is None
                or earliest.effective_from > self.window_start
            ):
                earliest.effective_from = self.window_start
                earliest.save(update_fields=["effective_from"])
                self.counts["lcr_backdated"] += 1

    def _ensure_lcr(self, user):
        if user and not UserCost.objects.filter(user=user).exists():
            UserCost.objects.create(
                user=user,
                effective_from=self.window_start,
                cost_per_hour=Decimal(random.randint(30, 120)),
            )
            self.counts["lcr_created"] += 1

    # -- Billing codes -------------------------------------------------------

    def _code(self, code_str, *, client=None, chargeable=False, internal=False):
        obj, created = BillingCode.objects.get_or_create(
            code=code_str,
            defaults={
                "client": client,
                "is_chargeable": chargeable,
                "is_internal": internal,
            },
        )
        if created:
            self.counts["codes"] += 1
        return obj

    def _assign(self, code, *, job=None, phase=None, project=None, start=None, end=None):
        _obj, created = BillingCodeAssignment.objects.get_or_create(
            code=code,
            job=job,
            phase=phase,
            project=project,
            start_date=start,
            end_date=end,
            defaults={"created_by": self.marker},
        )
        if created:
            self.counts["assignments"] += 1

    @staticmethod
    def _client_short(client):
        s = (client.short_name or "").strip()
        if not s:
            s = "".join(w[0] for w in client.name.split() if w)
        s = "".join(ch for ch in s.upper() if ch.isalnum())[:6]
        return s or "CLT"

    def _client_code_str(self, client):
        return "GB-{}-{}".format(self._client_short(client), client.id)

    def _codes_for_job(self, i, job):
        phases = list(job.phases.all())

        # Job-level "main" code (undated) — inherited by phases with no own code.
        main = self._code("{}-MAIN".format(job.id), client=job.client, chargeable=True)
        self._assign(main, job=job)

        # Client-level code, reused across all of this client's jobs (job-level).
        if job.client_id:
            client_code = self._code(
                self._client_code_str(job.client), client=job.client, chargeable=True
            )
            self._assign(client_code, job=job)

        # Internal / WBS code sprinkled onto every 6th job (job-level).
        if i % 6 == 0:
            wbs = self._code(
                INTERNAL_WBS_CODES[(i // 6) % len(INTERNAL_WBS_CODES)],
                client=None,
                chargeable=False,
                internal=True,
            )
            self._assign(wbs, job=job)

        # Phase-level override on a second phase (every 2nd job with >=2 phases).
        if len(phases) >= 2 and i % 2 == 0:
            p = phases[1]
            override = self._code(
                "{}-P{}".format(job.id, getattr(p, "phase_number", 2)),
                client=job.client,
                chargeable=True,
            )
            self._assign(override, phase=p)

        # Date-bound treatments on the first phase (kept clear of the override).
        p0 = phases[0] if phases else None
        window = self._phase_window(p0) if p0 else None
        if window:
            p_start, p_mid, _p_end = window
            if i % 4 == 0:
                # Own dated code covering only the first half -> phase does NOT
                # inherit the job code, so the second half is UNCODED.
                h1 = self._code("{}-H1".format(job.id), client=job.client, chargeable=True)
                self._assign(h1, phase=p0, start=p_start, end=p_mid)
            elif i % 3 == 0:
                # Undated + dated overlap on the same phase -> first half emits
                # both codes (show-all-applicable), second half just the undated.
                split = self._code(
                    "{}-SPLIT".format(job.id), client=job.client, chargeable=True
                )
                h1 = self._code("{}-H1".format(job.id), client=job.client, chargeable=True)
                self._assign(split, phase=p0)
                self._assign(h1, phase=p0, start=p_start, end=p_mid)

    @staticmethod
    def _phase_window(phase):
        """(start, midpoint, end) dates from a phase's timeslots, or None."""
        agg = phase.timeslots.all()
        starts = [s.start.date() for s in agg]
        ends = [s.end.date() for s in agg]
        if not starts:
            return None
        p_start, p_end = min(starts), max(ends)
        p_mid = p_start + (p_end - p_start) // 2
        return p_start, p_mid, p_end

    # -- Revenue -------------------------------------------------------------

    def _set_revenue(self, job):
        hours = Decimal("0")
        for slot in TimeSlot.objects.filter(
            phase__job=job, slot_type_id=DefaultTimeSlotTypes.DELIVERY
        ):
            hours += slot.get_business_hours()
        hours_in_day = Decimal(str(job.get_hours_in_day() or settings.DEFAULT_HOURS_IN_DAY))
        days = (hours / hours_in_day) if hours_in_day else Decimal("0")
        job.revenue = Decimal(round(days)) * self.day_rate
        job.save(update_fields=["revenue"])
        self.counts["jobs_revenued"] += 1

    # -- Support team --------------------------------------------------------

    def _apply_support(self, job):
        unit = job.unit
        if not unit or not unit.support_template.exists():
            return
        unit.apply_support_template_to_job(job)
        for tmpl in unit.support_template.select_related("user"):
            self._ensure_lcr(tmpl.user)
        self.counts["support_applied"] += 1

    def _seed_draws(self, jobs, budget):
        """Add draw-downs across the current and previous timesheet periods for a
        spread of support members (only where a budget in hours resolves)."""
        if budget <= 0:
            return
        cur = period_for_date(timezone.now().date())
        prev = previous_period(timezone.now().date())
        periods = [prev, cur]

        made = 0
        support_jobs = [j for j in jobs if j.unit and j.unit.support_template.exists()]
        for job in support_jobs:
            if made >= budget:
                break
            b = build_job_support_budget(job)
            roles = {r.user_id: r for r in job.supporting_team.all()}
            for user_id, member in b["per_member"].items():
                if made >= budget:
                    break
                hours = member.get("budget_hours")
                role = roles.get(user_id)
                if not hours or hours <= 0 or role is None:
                    continue
                # Draw ~30% then ~20% of budget across the two periods.
                for (p_start, p_end), frac in zip(periods, (Decimal("0.3"), Decimal("0.2"))):
                    drawn = (hours * frac).quantize(Decimal("0.01"))
                    if drawn <= 0:
                        continue
                    _obj, created = SupportBudgetDraw.objects.get_or_create(
                        support_role=role,
                        period_start=p_start,
                        period_end=p_end,
                        defaults={
                            "user": role.user,
                            "hours_drawn": drawn,
                            "created_by": self.marker,
                        },
                    )
                    # Count existing draws toward the cap too, so re-runs converge
                    # (a member already drawn for a period isn't drawn again).
                    made += 1
                    if created:
                        self.counts["draws"] += 1

    # -- Clear ---------------------------------------------------------------

    def _clear(self):
        self.stdout.write(self.style.WARNING("Clearing generated billing/support test data..."))
        # Draws + assignments are tagged with the marker user.
        SupportBudgetDraw.objects.filter(created_by=self.marker).delete()
        BillingCodeAssignment.objects.filter(created_by=self.marker).delete()
        # Re-derive the generated code strings and delete those codes (cascades
        # any remaining assignments).
        code_strs = set(INTERNAL_WBS_CODES)
        for job in Job.objects.select_related("client").all():
            code_strs.add("{}-MAIN".format(job.id))
            code_strs.add("{}-H1".format(job.id))
            code_strs.add("{}-SPLIT".format(job.id))
            for p in job.phases.all():
                code_strs.add("{}-P{}".format(job.id, getattr(p, "phase_number", 2)))
            if job.client_id:
                code_strs.add(self._client_code_str(job.client))
        deleted, _ = BillingCode.objects.filter(code__in=code_strs).delete()
        self.stdout.write("  Removed {} billing-code rows (+ cascades).".format(deleted))

    # -- Reporting -----------------------------------------------------------

    def _report(self, cleared=False):
        if cleared:
            self.stdout.write(self.style.SUCCESS("Clear complete."))
            return
        c = self.counts
        self.stdout.write(
            self.style.SUCCESS(
                "Done. codes={codes} assignments={assignments} "
                "jobs_revenued={jobs_revenued} lcr_backdated={lcr_backdated} "
                "lcr_created={lcr_created} support_applied={support_applied} "
                "draws={draws}".format(**c)
            )
        )
