# Generated by Django 5.2.3 on 2025-09-24 13:43

import chaotica_utils.utils.common
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobtracker", "0056_skill_prerequisites_skill_related_skills"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QAReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                (
                    "weeks_back_config",
                    models.IntegerField(
                        default=4, help_text="Number of weeks back used for selection"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "technical_accuracy",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="1 = Poor, 5 = Excellent",
                        null=True,
                    ),
                ),
                (
                    "report_quality",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="1 = Poor, 5 = Excellent",
                        null=True,
                    ),
                ),
                (
                    "timeliness",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="1 = Poor, 5 = Excellent",
                        null=True,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_reviews",
                        to="jobtracker.phase",
                    ),
                ),
                (
                    "reviewed_user",
                    models.ForeignKey(
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        related_name="qa_reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=models.SET(
                            chaotica_utils.utils.common.get_sentinel_user
                        ),
                        related_name="qa_reviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Review",
                "verbose_name_plural": "QA Reviews",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="QAReviewConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weeks_back",
                    models.IntegerField(
                        default=4,
                        help_text="Number of weeks to look back for eligible reports",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa_config",
                        to="jobtracker.organisationalunit",
                    ),
                ),
            ],
            options={
                "verbose_name": "QA Review Configuration",
                "verbose_name_plural": "QA Review Configurations",
            },
        ),
    ]
