# Generated by Django 5.2.3 on 2025-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa_reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qareview",
            name="report_quality",
        ),
        migrations.RemoveField(
            model_name="qareview",
            name="technical_accuracy",
        ),
        migrations.RemoveField(
            model_name="qareview",
            name="timeliness",
        ),
        migrations.AlterField(
            model_name="qareview",
            name="notes",
            field=models.TextField(blank=True, help_text="Review notes and feedback"),
        ),
    ]
