version: "3.8"

services:
  web:
    image: brainthee/chaotica:latest
    command: gunicorn chaotica.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
    environment:
      - DEBUG=0 # Set to 1 to enable Django's Debug mode
      - SECRET_KEY=CHANGE_ME # No really - change it!
      - DJANGO_ENV=dev
      - DJANGO_VERSION=latest
      - RUN_COLLECTSTATIC=false
      - TZ=Europe/London

      - SQL_ENGINE=django.db.backends.mysql # The database engine to use. If blank, uses SQLite
      # Be sure to match these to the vars in the DB service below
      - RDS_DB_NAME=chaotica
      - RDS_USERNAME=chaotica
      - RDS_PASSWORD=Hunter2 # Change this if in production...
      - RDS_HOSTNAME=db
      - RDS_PORT=3306
    depends_on:
      - db

  db:
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=chaotica
      - MARIADB_USER=chaotica
      - MARIADB_PASSWORD=Hunter2
      - MARIADB_ROOT_PASSWORD=Hunter2

  nginx:
    image: nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./nginx.conf:/etc/nginx/conf.d/chaotica.conf
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  mariadb_data:
  static_volume:
  media_volume:
